const countryMeta = {
  MEX: { name: "墨西哥", nameEn: "Mexico", capital: "墨西哥城", region: "north", flag: "https://flagcdn.com/w160/mx.png" },
  GTM: { name: "危地马拉", nameEn: "Guatemala", capital: "危地马拉城", region: "north", flag: "https://flagcdn.com/w160/gt.png" },
  SLV: { name: "萨尔瓦多", nameEn: "El Salvador", capital: "圣萨尔瓦多", region: "north", flag: "https://flagcdn.com/w160/sv.png" },
  HND: { name: "洪都拉斯", nameEn: "Honduras", capital: "特古西加尔巴", region: "north", flag: "https://flagcdn.com/w160/hn.png" },
  NIC: { name: "尼加拉瓜", nameEn: "Nicaragua", capital: "马那瓜", region: "north", flag: "https://flagcdn.com/w160/ni.png" },
  CRI: { name: "哥斯达黎加", nameEn: "Costa Rica", capital: "圣何塞", region: "north", flag: "https://flagcdn.com/w160/cr.png" },
  PAN: { name: "巴拿马", nameEn: "Panama", capital: "巴拿马城", region: "north", flag: "https://flagcdn.com/w160/pa.png" },
  CUB: { name: "古巴", nameEn: "Cuba", capital: "哈瓦那", region: "caribbean", flag: "https://flagcdn.com/w160/cu.png" },
  HTI: { name: "海地", nameEn: "Haiti", capital: "太子港", region: "caribbean", flag: "https://flagcdn.com/w160/ht.png" },
  DOM: { name: "多米尼加", nameEn: "Dominican Republic", capital: "圣多明各", region: "caribbean", flag: "https://flagcdn.com/w160/do.png" },
  COL: { name: "哥伦比亚", nameEn: "Colombia", capital: "波哥大", region: "andean", flag: "https://flagcdn.com/w160/co.png" },
  VEN: { name: "委内瑞拉", nameEn: "Venezuela", capital: "加拉加斯", region: "andean", flag: "https://flagcdn.com/w160/ve.png" },
  ECU: { name: "厄瓜多尔", nameEn: "Ecuador", capital: "基多", region: "andean", flag: "https://flagcdn.com/w160/ec.png" },
  PER: { name: "秘鲁", nameEn: "Peru", capital: "利马", region: "andean", flag: "https://flagcdn.com/w160/pe.png" },
  BRA: { name: "巴西", nameEn: "Brazil", capital: "巴西利亚", region: "brazil", flag: "https://flagcdn.com/w160/br.png" },
  BOL: { name: "玻利维亚", nameEn: "Bolivia", capital: "苏克雷/拉巴斯", region: "andean", flag: "https://flagcdn.com/w160/bo.png" },
  PRY: { name: "巴拉圭", nameEn: "Paraguay", capital: "亚松森", region: "south", flag: "https://flagcdn.com/w160/py.png" },
  CHL: { name: "智利", nameEn: "Chile", capital: "圣地亚哥", region: "south", flag: "https://flagcdn.com/w160/cl.png" },
  ARG: { name: "阿根廷", nameEn: "Argentina", capital: "布宜诺斯艾利斯", region: "south", flag: "https://flagcdn.com/w160/ar.png" },
  URY: { name: "乌拉圭", nameEn: "Uruguay", capital: "蒙得维的亚", region: "south", flag: "https://flagcdn.com/w160/uy.png" }
};

const regionColors = {
  north: "#E07A5F",
  caribbean: "#3D405B",
  andean: "#81B29A",
  south: "#F2CC8F",
  brazil: "#9B5DE5"
};

const countryData = {
  MEX: {
    population: 130262000, area: 1964375, language: "西班牙语 + 68种土著语言", currency: "比索 (MXN)",
    gdp: 1788000000000, gdpPerCapita: 13700, gini: 45.4, hdi: 0.781,
    overview: "墨西哥是拉美第二大经济体，全球第15大经济体。这片土地上孕育了奥尔梅克、玛雅、特奥蒂瓦坎和阿兹特克等辉煌文明。1821年独立后经历帝国、共和、独裁、革命与现代化的漫长历程。今日墨西哥是全球制造业重镇（近岸外包热门目的地），与美国深度整合，但也深陷毒品战争与暴力漩涡。社会呈两极化：北部工业带相对富裕，南部各州以印第安人为主，贫困与边缘化严重。",
    history: [
      { year: "前1500-前400", event: "奥尔梅克文明兴起，被视为中美洲母文化，创造巨型头像雕塑" },
      { year: "前200-900", event: "玛雅古典期，数学天文历法达到极高水准，蒂卡尔帕伦克等城邦繁荣" },
      { year: "1325", event: "阿兹特克人在特斯科科湖建立特诺奇蒂特兰，后成为前哥伦布时代最大城市之一" },
      { year: "1519-1521", event: "科尔特斯率领西班牙远征军，联合特拉斯卡拉等部落，征服阿兹特克帝国" },
      { year: "1535-1821", event: "新西班牙总督辖区时期，白银开采驱动全球贸易网络，印第安人口因疾病和剥削锐减90%" },
      { year: "1810", event: "伊达尔戈神父在多洛雷斯发出独立号召，发动大规模起义" },
      { year: "1821", event: "伊图尔维德发动三保证军运动，墨西哥正式独立" },
      { year: "1824", event: "联邦共和国宪法颁布，确立联邦制，但政局持续动荡" },
      { year: "1836", event: "德克萨斯独立战争，随后并入美国" },
      { year: "1846-1848", event: "美墨战争，墨西哥丧失今加利福尼亚新墨西哥亚利桑那等大片领土（占国土面积55%）" },
      { year: "1857", event: "自由派宪法颁布，引发改革战争 (1858-1861)" },
      { year: "1862-1867", event: "法国干涉战争，马克西米利安皇帝短暂统治后被处决" },
      { year: "1876-1911", event: "波菲里奥迪亚斯独裁统治35年，推动现代化但加剧土地集中" },
      { year: "1910-1920", event: "墨西哥革命，卡兰萨萨帕塔比利亚等各方势力混战，约150-200万人死亡" },
      { year: "1917", event: "现行宪法颁布，全球最进步的宪法之一，规定土地改革劳工权利国家资源主权" },
      { year: "1929", event: "革命制度党 (PRI) 成立，开启长达71年的事实一党执政" },
      { year: "1938", event: "卡德纳斯总统石油国有化，建立 PEMEX，深刻塑造民族主义意识形态" },
      { year: "1968", event: "特拉特洛尔科大屠杀，奥运前夕政府屠杀数百学生示威者" },
      { year: "1994", event: "北美自贸协定 (NAFTA) 生效；同日萨帕塔民族解放军在恰帕斯州起义" },
      { year: "2000", event: "福克斯当选总统，PRI 一党统治终结，实现政党轮替" },
      { year: "2006-2012", event: "卡尔德龙发动毒品战争，军事打击 cartels，导致约15万人死亡" },
      { year: "2018", event: "洛佩斯奥夫拉多尔 (AMLO) 以压倒性优势当选，开启第四次变革" },
      { year: "2024", event: "克劳迪娅辛鲍姆当选，成为墨西哥首位女总统，延续 MORENA 执政" }
    ],
    politics: {
      system: "联邦总统制共和国",
      headOfState: "克劳迪娅辛鲍姆",
      rulingParty: "国家复兴运动 (MORENA)",
      legislature: "两院制：参议院128席，众议院500席",
      lastElection: "2024年总统大选",
      notes: "辛鲍姆为能源学家出身，曾任墨西哥城市长。延续 AMLO 的民粹主义路线，但试图塑造更温和的技术官僚形象。",
      constitutionalHistory: "1917年宪法为全球最进步宪法之一，历经数百次修正。2000年后司法独立逐步增强，但2019年 AMLO 推动的司法改革引发法治担忧。",
      foreignRelations: "美国为最重要双边关系（经贸移民安全），同时积极拓展与欧盟亚太关系。2023年取代中国成为美国最大贸易伙伴。",
      internationalOrgs: ["联合国", "OECD", "USMCA", "太平洋联盟", "拉美和加勒比国家共同体 (CELAC)"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:3.3},{year:2016,val:2.9},{year:2017,val:2.1},{year:2018,val:2.2},{year:2019,val:-0.2},{year:2020,val:-8.3},{year:2021,val:4.7},{year:2022,val:3.9},{year:2023,val:3.2}],
      sectors: [{name:"服务业",value:62},{name:"工业",value:31},{name:"农业",value:4}],
      exports: [{name:"汽车及零部件",value:28},{name:"电子产品",value:18},{name:"石油",value:12},{name:"农产品",value:10},{name:"机械",value:8}],
      inflation: 4.7, unemployment: 2.8,
      tradeBalance: -24000000000,
      mainPartners: ["美国 (80%)", "中国", "加拿大", "德国"],
      debtToGdp: 49.8,
      fdi: 36000000000,
      exchangeRate: "17.2 MXN/USD (2024)",
      mainCompanies: "PEMEX (石油), Cemex (水泥), America Movil (电信), FEMSA (饮料零售), Grupo Bimbo (烘焙)"
    },
    society: {
      literacy: 95.4, lifeExpectancy: 75.1, urbanization: 81,
      povertyRate: 36.3, homicideRate: 23.3,
      educationExp: 4.0, healthExp: 5.4,
      ethnic: "混血 (62%), 印第安人 (21%), 白人 (15%), 其他 (2%)",
      internetPenetration: 78,
      fertilityRate: 1.8,
      gii: 0.296,
      climateRisk: "极高：干旱、飓风、海平面上升。2023年奥蒂斯飓风重创阿卡普尔科。",
      refugees: "接收约7万中美洲难民寻求庇护者，同时每年数十万墨西哥人北上美国。"
    }
  },

  GTM: {
    population: 18092000, area: 108889, language: "西班牙语 + 23种玛雅语言", currency: "格查尔 (GTQ)",
    gdp: 102000000000, gdpPerCapita: 5600, gini: 48.3, hdi: 0.663,
    overview: "危地马拉是中美洲人口最多的国家，也是玛雅文明的心脏地带。超过40%人口为印第安人，讲23种玛雅语言，是全球土著文化保存最完好的地区之一。然而殖民掠夺、种族歧视和内战创伤使这个国家长期深陷贫困与暴力。2023年种子运动的意外胜选带来民主希望，但司法系统仍被旧精英牢牢把控。",
    history: [
      { year: "前2000-900", event: "前古典期玛雅文明兴起，米拉多尔等早期城邦建立" },
      { year: "250-900", event: "玛雅古典期，蒂卡尔成为当时世界最大城市之一（人口10万），发明了零的概念" },
      { year: "900-1524", event: "后古典期，玛雅文明中心北移，与墨西哥中部文明交流加深" },
      { year: "1524-1541", event: "佩德罗德阿尔瓦拉多征服危地马拉，建立圣地亚哥城（今安提瓜）" },
      { year: "1542-1821", event: "危地马拉都督辖区时期，管辖中美洲大部，白银和可可经济" },
      { year: "1821", event: "独立宣言" },
      { year: "1822-1823", event: "短暂并入墨西哥帝国" },
      { year: "1823-1841", event: "中美洲联邦共和国时期，包括今危地马拉萨尔瓦多洪都拉斯尼加拉瓜哥斯达黎加" },
      { year: "1841", event: "联邦解体，危地马拉正式独立" },
      { year: "1871-1944", event: "自由派执政，咖啡经济兴起，土地大规模集中于德国移民和本国精英手中" },
      { year: "1944-1954", event: "十年之春，胡安何塞阿雷瓦洛和哈科沃阿本斯推行土地改革" },
      { year: "1954", event: "美国CIA策划政变，推翻民选阿本斯政府，联合果品公司利益是关键动因" },
      { year: "1960", event: "内战爆发，左翼游击队与军政府对抗，美国提供大量军事援助" },
      { year: "1963-1986", event: "军人反复干政，建立右翼威权统治，实施系统性反印第安人暴力" },
      { year: "1982", event: "里奥内格罗大屠杀，军队杀害177名玛雅村民，为内战中最严重暴行之一" },
      { year: "1996", event: "签署坚定持久和平协定，结束36年内战，约20万人死亡4.5万人失踪" },
      { year: "1999", event: "真相委员会发布报告，确认政府对玛雅人实施种族灭绝" },
      { year: "2015", event: "奥托佩雷斯莫利纳总统因腐败丑闻辞职入狱" },
      { year: "2019", event: "亚历杭德罗贾马太当选总统，但持续打压司法独立" },
      { year: "2023", event: "贝尔纳多阿雷瓦洛和种子运动意外胜选，但遭司法系统阻挠" },
      { year: "2024", event: "阿雷瓦洛就职，承诺反腐和恢复民主制度" }
    ],
    politics: {
      system: "总统制共和国",
      headOfState: "贝尔纳多阿雷瓦洛",
      rulingParty: "种子运动 (Semilla)",
      legislature: "一院制：国会160席",
      lastElection: "2023年",
      notes: "阿雷瓦洛为前外交官和学者之子，以反腐为主轴。就职后面临建制派检察官持续法律战。",
      constitutionalHistory: "1985年宪法，历经多次修正。2015年后反腐浪潮推动制度改革，但旧精英网络仍控制关键机构。",
      foreignRelations: "美国为最大贸易伙伴和安全盟友，近年积极拓展与台湾（仅余12个邦交国之一）和中国大陆关系。",
      internationalOrgs: ["联合国", "中美洲一体化体系 (SICA)", "美洲国家组织 (OAS)", "中美洲议会 (PARLACEN)"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:4.2},{year:2016,val:3.1},{year:2017,val:2.8},{year:2018,val:3.3},{year:2019,val:3.8},{year:2020,val:-1.8},{year:2021,val:8.0},{year:2022,val:4.1},{year:2023,val:3.5}],
      sectors: [{name:"服务业",value:58},{name:"工业",value:24},{name:"农业",value:14}],
      exports: [{name:"咖啡",value:12},{name:"糖",value:9},{name:"香蕉",value:8},{name:"服装",value:20},{name:"蔬菜",value:7}],
      inflation: 4.5, unemployment: 3.1,
      tradeBalance: -8200000000,
      mainPartners: ["美国", "中美洲邻国", "墨西哥"],
      debtToGdp: 29.0,
      fdi: 1300000000,
      exchangeRate: "7.8 GTQ/USD (长期盯住美元浮动)",
      mainCompanies: "CMI (多元化集团), Tigo (电信), Banco Industrial, Grupo Heredia (航空)"
    },
    society: {
      literacy: 83.0, lifeExpectancy: 74.5, urbanization: 52,
      povertyRate: 55.1, homicideRate: 17.3,
      educationExp: 3.2, healthExp: 4.1,
      ethnic: "混血 (42%), 印第安人 (41%), 白人 (17%)",
      internetPenetration: 65,
      fertilityRate: 2.2,
      gii: 0.470,
      climateRisk: "极高：飓风、干旱、山体滑坡。2020年飓风伊塔和约塔造成毁灭性影响。",
      refugees: "接收少量中美洲难民；每年约数万危地马拉人北上美国。"
    }
  },

  SLV: {
    population: 6364000, area: 21041, language: "西班牙语", currency: "美元 (USD)",
    gdp: 35000000000, gdpPerCapita: 5500, gini: 38.8, hdi: 0.674,
    overview: "萨尔瓦多是中美洲面积最小、人口密度最高的国家。1932年拉马塔萨大屠杀后，印第安人文化几乎被根除。1980年代残酷内战留下深刻创伤。2021年成为全球首个将比特币定为法定货币的国家，引发全球争议。纳伊布布克尔总统以铁腕打击帮派著称，将谋杀率从全球最高之一降至接近历史最低，但其威权倾向、宪法任期限制操作和比特币实验也使外界担忧民主倒退。",
    history: [
      { year: "前1500", event: "皮皮人定居，受玛雅文化影响" },
      { year: "1524-1525", event: "佩德罗德阿尔瓦拉多征服萨尔瓦多" },
      { year: "1821", event: "脱离西班牙独立" },
      { year: "1822-1823", event: "短暂并入墨西哥帝国" },
      { year: "1823-1841", event: "中美洲联邦共和国成员" },
      { year: "1841", event: "正式独立建国" },
      { year: "1880s-1920s", event: "咖啡寡头统治，14家族控制经济和政治" },
      { year: "1932", event: "拉马塔萨 (La Matanza) 大屠杀，军政府杀害约3万印第安人和农民，Pipil语此后几乎灭绝" },
      { year: "1948-1979", event: "军事政变循环，政党名义上执政但军人幕后操控" },
      { year: "1979", event: "改革军政府上台，但无法阻止左翼游击队壮大" },
      { year: "1980-1992", event: "内战，法拉本多马蒂民族解放阵线 (FMLN) 与右翼军政府敢死队对抗，约7.5万人死亡" },
      { year: "1980", event: "奥斯卡罗梅罗大主教在主持弥撒时被暗杀，成为解放神学殉道者" },
      { year: "1989", event: "耶稣会六神甫及家属被军方暗杀，引发国际谴责" },
      { year: "1992", event: "签署查普尔特佩克和平协定，FMLN 转为政党" },
      { year: "1994", event: "首次完全自由选举，民族主义共和联盟 (ARENA) 胜选" },
      { year: "2001", event: "地震造成重大破坏；同年全面美元化，废除科朗" },
      { year: "2009", event: "毛里西奥富内斯 (FMLN) 当选，结束右翼20年执政" },
      { year: "2015", event: "谋杀率达到峰值每10万人103起，成为全球非战区最高" },
      { year: "2019", event: "纳伊布布克尔当选总统，承诺打破传统两党格局" },
      { year: "2020", event: "COVID期间军队入驻议会，布克尔展示强人姿态" },
      { year: "2021", event: "通过比特币法，9月7日正式成为法定货币" },
      { year: "2022", event: "紧急状态法下大规模扫黑，逮捕约7万疑似帮派成员" },
      { year: "2024", event: "布克尔以87%得票率连任，但参选资格存在宪法争议" }
    ],
    politics: {
      system: "总统制共和国",
      headOfState: "纳伊布布克尔",
      rulingParty: "新思想 (Nuevas Ideas)",
      legislature: "一院制：议会84席",
      lastElection: "2024年连任",
      notes: "布克尔为前圣萨尔瓦多市长，利用社交媒体建立个人崇拜。2021年后控制议会超级多数，逐步削弱司法独立。",
      constitutionalHistory: "1983年宪法禁止总统连任，但布克尔通过休假策略让亲信代理六个月规避限制，最高法院随后裁定可连任。",
      foreignRelations: "与美国关系复杂（安全合作紧密，但布克尔批评美国干涉内政）。中国是第二大贸易伙伴。与台湾保持邦交。",
      internationalOrgs: ["联合国", "中美洲一体化体系 (SICA)", "中美洲议会 (PARLACEN)", "美洲国家组织 (OAS，曾威胁退出)"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:2.4},{year:2016,val:2.5},{year:2017,val:2.3},{year:2018,val:2.9},{year:2019,val:2.4},{year:2020,val:-7.9},{year:2021,val:11.2},{year:2022,val:2.8},{year:2023,val:3.5}],
      sectors: [{name:"服务业",value:64},{name:"工业",value:26},{name:"农业",value:6}],
      exports: [{name:"纺织品",value:28},{name:"电器",value:12},{name:"糖",value:8},{name:"咖啡",value:6}],
      inflation: 2.1, unemployment: 3.0,
      tradeBalance: -5500000000,
      mainPartners: ["美国", "危地马拉", "洪都拉斯", "尼加拉瓜"],
      debtToGdp: 77.0,
      fdi: 600000000,
      exchangeRate: "美元化 (自2001年起)",
      mainCompanies: "Grupo Calleja (零售), TACA (航空，已合并), Texops (纺织)"
    },
    society: {
      literacy: 89.1, lifeExpectancy: 73.3, urbanization: 78,
      povertyRate: 24.1, homicideRate: 2.4,
      educationExp: 3.9, healthExp: 5.2,
      ethnic: "混血 (86%), 白人 (13%), 印第安人 (1%)",
      internetPenetration: 62,
      fertilityRate: 1.8,
      gii: 0.381,
      climateRisk: "高：火山活动、地震、飓风。圣米格尔火山和圣萨尔瓦多火山活跃。",
      refugees: "约10-15万萨尔瓦多人居住在美国（TPS身份）；近年因治安改善，移民略有下降。"
    }
  },

  HND: {
    population: 10789000, area: 112492, language: "西班牙语", currency: "伦皮拉 (HNL)",
    gdp: 33000000000, gdpPerCapita: 3100, gini: 52.1, hdi: 0.624,
    overview: "洪都拉斯是中美洲最贫困、最暴力的国家之一，长期被腐败、贩毒和军事政变困扰。2009年政变后民主严重倒退。2021年希奥玛拉卡斯特罗成为首位女总统，但治理能力受限。2023年与中国建交，与台湾断交。洪都拉斯是中美洲北三角移民潮的主要来源国之一，每年数万人北上寻求庇护。",
    history: [
      { year: "1502", event: "哥伦布第四次航行抵达洪都拉斯海岸" },
      { year: "1524-1539", event: "西班牙征服，建立格拉西亚斯阿迪奥斯等定居点" },
      { year: "1821", event: "独立" },
      { year: "1823-1838", event: "中美洲联邦共和国成员" },
      { year: "1838", event: "正式独立建国" },
      { year: "1860s-1900s", event: "香蕉共和国时代，美国联合果品公司控制经济命脉和铁路" },
      { year: "1932-1949", event: "蒂武西奥卡里亚斯安迪诺独裁统治" },
      { year: "1954", event: "香蕉工人大罢工，推动劳工权利发展" },
      { year: "1963", event: "军事政变推翻民选总统比列达莫拉莱斯" },
      { year: "1969", event: "与萨尔瓦多爆发足球战争，持续100小时，约3000人死亡" },
      { year: "1980s", event: "尼加拉瓜反政府战争波及洪都拉斯，美国利用洪领土训练 Contra" },
      { year: "1998", event: "飓风米奇造成毁灭性破坏，约7000人死亡，经济损失相当于年GDP的70%" },
      { year: "2009", event: "军事政变推翻总统塞拉亚，引发国际孤立和民主倒退" },
      { year: "2012-2017", event: "胡安奥兰多埃尔南德斯 (JOH) 执政，2017年连任引发舞弊争议" },
      { year: "2021", event: "JOH 被引渡美国，面临毒品走私指控" },
      { year: "2021", event: "希奥玛拉卡斯特罗当选，成为首位女总统，结束了国民党的12年执政" },
      { year: "2023", event: "与中国建交，与台湾断交，获得基础设施投资承诺" },
      { year: "2023", event: "国会与总统对立，卡斯特罗推动公投建立制宪议会失败" }
    ],
    politics: {
      system: "总统制共和国",
      headOfState: "希奥玛拉卡斯特罗",
      rulingParty: "自由与重建党 (Libre)",
      legislature: "一院制：国会128席",
      lastElection: "2021年",
      notes: "卡斯特罗为前总统塞拉亚之妻，代表左翼联盟。但国会内部分裂严重，治理能力受限。",
      constitutionalHistory: "1982年宪法。2009年政变后，2010年通过禁止政变的修正案，但宪法修改仍频繁服务于政治目的。",
      foreignRelations: "美国为主要安全和经济伙伴。2023年转向中国后获得基础设施投资。与邻国关系因边境争端和移民问题紧张。",
      internationalOrgs: ["联合国", "中美洲一体化体系 (SICA)", "中美洲议会 (PARLACEN)", "美洲国家组织 (OAS)"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:3.6},{year:2016,val:3.8},{year:2017,val:4.8},{year:2018,val:3.7},{year:2019,val:2.7},{year:2020,val:-9.0},{year:2021,val:12.5},{year:2022,val:4.0},{year:2023,val:3.8}],
      sectors: [{name:"服务业",value:56},{name:"工业",value:27},{name:"农业",value:14}],
      exports: [{name:"咖啡",value:22},{name:"香蕉",value:12},{name:"棕榈油",value:10},{name:"服装",value:18}],
      inflation: 5.8, unemployment: 4.8,
      tradeBalance: -3600000000,
      mainPartners: ["美国", "中国", "危地马拉", "萨尔瓦多"],
      debtToGdp: 52.0,
      fdi: 500000000,
      exchangeRate: "24.7 HNL/USD",
      mainCompanies: "Grupo Karims (纺织), Lacthosa (乳制品), Dinant (棕榈油食品)"
    },
    society: {
      literacy: 87.2, lifeExpectancy: 73.1, urbanization: 59,
      povertyRate: 48.9, homicideRate: 31.1,
      educationExp: 5.1, healthExp: 4.5,
      ethnic: "混血 (90%), 印第安人 (7%), 非裔 (2%), 白人 (1%)",
      internetPenetration: 48,
      fertilityRate: 2.3,
      gii: 0.396,
      climateRisk: "极高：飓风、洪水、干旱。飓风米奇(1998)和埃塔约塔(2020)造成灾难性后果。",
      refugees: "每年数万人北上美国，为北三角移民潮主要来源国。国内约20万因暴力流离失所。"
    }
  },

  NIC: {
    population: 7046000, area: 130370, language: "西班牙语", currency: "科多巴 (NIO)",
    gdp: 16600000000, gdpPerCapita: 2400, gini: 46.2, hdi: 0.669,
    overview: "尼加拉瓜是中美洲面积最大的国家，拥有中美洲最大的淡水湖和独特的火山景观。经历桑地诺革命和反政府战争的创伤后，1990年代曾短暂民主化。但丹尼尔奥尔特加自2007年重新掌权以来，逐步建立家族独裁，打压所有反对派，使尼加拉瓜成为继委内瑞拉后西半球最专制的国家之一。经济因制裁和孤立而萎缩，但奥尔特加仍维持着一套忠诚者网络。",
    history: [
      { year: "前1200-1500", event: "尼加拉高原地区印第安部落活跃，与阿兹特克和玛雅文明有贸易联系" },
      { year: "1524", event: "西班牙征服，建立格拉纳达和莱昂两城" },
      { year: "1821", event: "脱离西班牙独立" },
      { year: "1823-1838", event: "中美洲联邦共和国成员" },
      { year: "1838", event: "正式独立" },
      { year: "1855-1857", event: "美国冒险家威廉沃克入侵，自封为总统，后被中美洲联军击败" },
      { year: "1893-1909", event: "何塞桑托斯塞拉亚自由主义执政，与美国关系恶化" },
      { year: "1912-1933", event: "美国多次军事干预和占领，建立国民警卫队" },
      { year: "1936", event: "安纳斯塔西奥索摩查加西亚通过政变掌权，建立家族独裁" },
      { year: "1936-1979", event: "索摩查家族统治43年，控制经济命脉，积累巨额财富" },
      { year: "1972", event: "马那瓜大地震摧毁首都，索摩查挪用国际援助，激发民怨" },
      { year: "1978", event: "记者佩德罗华金查莫罗被暗杀，引发全国罢工和起义" },
      { year: "1979", event: "桑地诺民族解放阵线 (FSLN) 推翻索摩查，丹尼尔奥尔特加进入执政委员会" },
      { year: "1981-1990", event: "反政府战争 (Contra War)，美国里根政府资助右翼游击队对抗桑地诺政府" },
      { year: "1984", event: "奥尔特加当选总统，国际观察员承认选举公正" },
      { year: "1990", event: "查莫罗夫人 (UNO) 胜选，结束桑地诺执政" },
      { year: "1996", event: "阿莱曼 (自由党) 当选，开启腐败新纪元" },
      { year: "2006", event: "奥尔特加与自由党达成协议降低选举门槛，FSLN 重返权力" },
      { year: "2007", event: "奥尔特加再次就任总统" },
      { year: "2014", event: "宪法修改取消总统任期限制" },
      { year: "2018", event: "社保改革引发大规模抗议，政府镇压造成300余人死亡" },
      { year: "2021", event: "逮捕所有主要反对派候选人，奥尔特加夫妇当选" },
      { year: "2022", event: "大规模流亡开始，约10万余尼加拉瓜人逃离" },
      { year: "2024", event: "奥尔特加再次当选，国际社会普遍不予承认" }
    ],
    politics: {
      system: "总统制共和国 (事实威权)",
      headOfState: "丹尼尔奥尔特加",
      rulingParty: "桑地诺民族解放阵线 (FSLN)",
      legislature: "一院制：国民议会92席 (FSLN控制超三分之二)",
      lastElection: "2021年 (被广泛质疑)",
      notes: "奥尔特加与妻子罗萨里奥穆里略 (副总统) 共同掌权。所有独立媒体NGO教会均被关闭或流亡。",
      constitutionalHistory: "1987年宪法为桑地诺革命成果。2000年后历经多次修正削弱制衡机制，2014年取消任期限制。",
      foreignRelations: "与美国断交边缘，俄罗斯为重要盟友。中国为第二大贸易伙伴。与台湾保持邦交至2021年（已断交）。",
      internationalOrgs: ["联合国", "中美洲一体化体系 (SICA，实际被边缘化)", "美洲国家组织 (OAS，2018年后被冻结)", " Alba-TCP"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:4.9},{year:2016,val:4.6},{year:2017,val:4.8},{year:2018,val:-3.4},{year:2019,val:-3.4},{year:2020,val:-3.0},{year:2021,val:10.3},{year:2022,val:3.8},{year:2023,val:4.0}],
      sectors: [{name:"服务业",value:55},{name:"工业",value:22},{name:"农业",value:16}],
      exports: [{name:"咖啡",value:18},{name:"牛肉",value:14},{name:"黄金",value:12},{name:"花生",value:6}],
      inflation: 7.2, unemployment: 4.1,
      tradeBalance: -1800000000,
      mainPartners: ["美国", "中国", "墨西哥", "萨尔瓦多"],
      debtToGdp: 47.0,
      fdi: 300000000,
      exchangeRate: "36.5 NIO/USD",
      mainCompanies: " Alba 集团 (国家控制), Pellas 集团 (多元化), Grupo Promerica (金融)"
    },
    society: {
      literacy: 82.6, lifeExpectancy: 74.5, urbanization: 60,
      povertyRate: 43.0, homicideRate: 7.5,
      educationExp: 4.0, healthExp: 5.2,
      ethnic: "混血 (69%), 白人 (17%), 非裔 (9%), 印第安人 (5%)",
      internetPenetration: 55,
      fertilityRate: 2.3,
      gii: 0.364,
      climateRisk: "高：飓风、干旱、火山活动。马那瓜湖污染严重。",
      refugees: "约10万余人流亡（2018年后），主要前往哥斯达黎加、美国和西班牙。"
    }
  },

  CRI: {
    population: 5213000, area: 51100, language: "西班牙语", currency: "科朗 (CRC)",
    gdp: 91000000000, gdpPerCapita: 17500, gini: 47.2, hdi: 0.809,
    overview: "哥斯达黎加是拉美民主标杆，1948年废除军队，将资源投入教育和医疗。经济以生态旅游、电子出口和离岸服务为主。社会指标在地区领先，但财政赤字和公共债务持续攀升。近年来成为数字游民和退休移民热门目的地。",
    history: [
      { year: "前10000-前1500", event: "最早印第安人定居，形成多个部落文化" },
      { year: "1502", event: "哥伦布第四次航行抵达卡里亚里湾" },
      { year: "1563", event: "西班牙建立卡塔戈城，成为殖民中心" },
      { year: "1821", event: "独立，后并入中美洲联邦" },
      { year: "1838", event: "联邦解体，正式独立" },
      { year: "1856-1857", event: "成功抵御威廉沃克 filibuster 入侵" },
      { year: "1889", event: "建立民主制度，成为拉美最早实行男子普选的国家之一" },
      { year: "1917", event: "蒂诺科短暂独裁被推翻，民主传统得以延续" },
      { year: "1940-1944", event: "卡尔德隆总统推行社会改革，建立社会保障体系" },
      { year: "1948", event: "内战（历时44天），约2000人死亡；随后废除军队，成为世界首个主动废除军队的国家" },
      { year: "1949", event: "何塞菲格雷斯将权力移交给民选政府，奠定民主传统" },
      { year: "1955-1978", event: "民族解放党 (PLN) 与社会基督团结党交替执政" },
      { year: "1987", event: "总统阿里亚斯获诺贝尔和平奖，推动中美洲和平计划" },
      { year: "2007", event: "与台湾断交，与中国建交" },
      { year: "2010", event: "与中国自贸协定生效" },
      { year: "2014", event: "索利斯总统推动财政改革，引发大规模抗议" },
      { year: "2018", event: "阿尔瓦拉多当选，承诺实现碳中和（2050年目标）" },
      { year: "2020", event: "COVID冲击旅游业，经济收缩4.1%" },
      { year: "2022", event: "查韦斯当选总统，主打反腐和财政紧缩" },
      { year: "2022-2024", event: "财政危机持续，与国际货币基金组织谈判救助" }
    ],
    politics: {
      system: "总统制共和国",
      headOfState: "罗德里戈查韦斯",
      rulingParty: "社会民主进步党 (PPSD)",
      legislature: "一院制：立法大会57席",
      lastElection: "2022年",
      notes: "查韦斯为前世界银行经济学家，以反腐和财政紧缩为号召，但与媒体关系紧张，多次公开攻击记者。",
      constitutionalHistory: "1949年宪法，历经多次修正。废除军队写入宪法，成为国家身份核心。司法独立相对较强。",
      foreignRelations: "美国为最重要安全和经济伙伴。与中国关系良好（2007年建交）。积极参与国际环保和气候议题。",
      internationalOrgs: ["联合国", "OECD", "中美洲一体化体系 (SICA)", "太平洋联盟", "美洲国家组织 (OAS)"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:3.7},{year:2016,val:4.2},{year:2017,val:4.2},{year:2018,val:2.6},{year:2019,val:2.2},{year:2020,val:-4.1},{year:2021,val:7.8},{year:2022,val:4.3},{year:2023,val:5.1}],
      sectors: [{name:"服务业",value:68},{name:"工业",value:22},{name:"农业",value:5}],
      exports: [{name:"医疗器械",value:28},{name:"香蕉",value:12},{name:"菠萝",value:10},{name:"咖啡",value:8},{name:"电子",value:15}],
      inflation: 0.9, unemployment: 7.8,
      tradeBalance: -4200000000,
      mainPartners: ["美国", "中国", "欧盟", "尼加拉瓜"],
      debtToGdp: 67.0,
      fdi: 2800000000,
      exchangeRate: "520 CRC/USD",
      mainCompanies: "Intel (前工厂), BAC Credomatic (金融), Florida Ice & Farm (饮料)"
    },
    society: {
      literacy: 97.9, lifeExpectancy: 80.3, urbanization: 83,
      povertyRate: 21.0, homicideRate: 17.2,
      educationExp: 6.9, healthExp: 7.4,
      ethnic: "白人混血 (83%), 其他 (17%)",
      internetPenetration: 85,
      fertilityRate: 1.5,
      gii: 0.239,
      climateRisk: "中高：飓风、山体滑坡、干旱。承诺2050年碳中和，可再生能源占比高。",
      refugees: "接收约3万尼加拉瓜难民（2018年后）；本国向北美移民较少。"
    }
  },

  PAN: {
    population: 4468000, area: 75420, language: "西班牙语", currency: "巴波亚/美元 (PAB/USD)",
    gdp: 82000000000, gdpPerCapita: 18400, gini: 49.2, hdi: 0.805,
    overview: "巴拿马因运河而闻名全球，运河收入占GDP重要部分。是拉美最繁荣国家之一，金融和物流服务发达。拥有大量离岸金融注册公司，是重要的区域航空枢纽。2024年当选新总统后面临财政压力和与美国在移民问题上的摩擦。",
    history: [
      { year: "前10000", event: "最早人类定居，形成多个印第安部落" },
      { year: "1501", event: "西班牙建立殖民据点" },
      { year: "1513", event: "巴尔博亚穿越地峡，首次看到太平洋" },
      { year: "1671", event: "海盗亨利摩根焚毁巴拿马城" },
      { year: "1821", event: "独立，并入大哥伦比亚" },
      { year: "1840s", event: "成为重要跨地峡贸易通道，大量美国移民前往加州淘金途经此地" },
      { year: "1855", event: "巴拿马铁路建成，世界第一大陆际铁路" },
      { year: "1881-1889", event: "法国费迪南德莱塞普斯尝试开凿运河，因疟疾和黄热病失败" },
      { year: "1903", event: "在美国支持下脱离哥伦比亚独立，签订《海-布诺-瓦里亚条约》" },
      { year: "1904-1914", event: "美国成功开凿巴拿马运河，工程约5600人死亡" },
      { year: "1964", event: "运河区国旗事件，巴拿马学生与美军冲突，21人死亡" },
      { year: "1968", event: "托里霍斯将军政变掌权，推动民族主义改革" },
      { year: "1977", event: "签署托里霍斯-卡特条约，承诺1999年移交运河" },
      { year: "1989", event: "美国入侵推翻诺列加军政府，约3500人死亡" },
      { year: "1999", event: "运河主权移交巴拿马，美军撤离" },
      { year: "2006", event: "全民公投通过运河扩建计划" },
      { year: "2016", event: "运河扩建工程竣工，可通过更大船只" },
      { year: "2017", event: "与中国建交（此前长期与台湾保持邦交）" },
      { year: "2023", event: "科布雷铜矿争议引发大规模环保抗议" },
      { year: "2024", event: "何塞劳尔穆利诺当选总统" }
    ],
    politics: {
      system: "总统制共和国",
      headOfState: "何塞劳尔穆利诺",
      rulingParty: "实现目标党 (RM)",
      legislature: "一院制：国民议会71席",
      lastElection: "2024年",
      notes: "穆利诺为前总统科尔蒂索支持的候选人，胜选延续执政联盟路线。面临财政赤字和环保压力。",
      constitutionalHistory: "1972年宪法，1983年民主化修正。运河主权和永久中立为核心条款。",
      foreignRelations: "美国为最重要伙伴（安全和运河），中国为重要贸易和投资伙伴。2024年因美国施压减少中国移民过境。",
      internationalOrgs: ["联合国", "OECD", "中美洲一体化体系 (SICA)", "美洲国家组织 (OAS)", "太平洋联盟"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:5.8},{year:2016,val:5.0},{year:2017,val:5.6},{year:2018,val:3.6},{year:2019,val:3.0},{year:2020,val:-17.7},{year:2021,val:15.3},{year:2022,val:10.8},{year:2023,val:7.5}],
      sectors: [{name:"服务业",value:72},{name:"工业",value:16},{name:"农业",value:3}],
      exports: [{name:"服务(运河/金融)",value:40},{name:"铜矿",value:15},{name:"香蕉",value:8},{name:"虾",value:6}],
      inflation: 1.5, unemployment: 7.5,
      tradeBalance: -4200000000,
      mainPartners: ["美国", "中国", "哥斯达黎加", "荷兰"],
      debtToGdp: 63.0,
      fdi: 5500000000,
      exchangeRate: "1 PAB = 1 USD (盯住美元)",
      mainCompanies: "Copa Airlines (航空), Banco General (金融), Grupo Rey (零售)"
    },
    society: {
      literacy: 95.7, lifeExpectancy: 78.7, urbanization: 69,
      povertyRate: 22.0, homicideRate: 11.1,
      educationExp: 3.2, healthExp: 5.3,
      ethnic: "混血 (65%), 白人 (14%), 非裔 (10%), 印第安人 (6%)",
      internetPenetration: 70,
      fertilityRate: 2.3,
      gii: 0.383,
      climateRisk: "高：海平面上升威胁沿海城市，干旱影响运河水位。",
      refugees: "约8万委内瑞拉难民和移民过境或定居；大量亚洲移民经此北上美国。"
    }
  },

  CUB: {
    population: 11194000, area: 109884, language: "西班牙语", currency: "比索 (CUP)",
    gdp: 107000000000, gdpPerCapita: 9500, gini: 38.0, hdi: 0.764,
    overview: "古巴是西半球唯一的社会主义国家，1959年革命后建立共产主义政权。拥有世界一流的医疗和教育体系，但经济长期受美国封锁和计划经济体制束缚。近年有限度开放私营经济（cuentapropistas）和旅游业，但2021年抗议浪潮后改革停滞。海外劳工输出（尤其是医生）是重要外汇来源。",
    history: [
      { year: "前4000", event: "最早的印第安人（泰诺人、西沃内人）定居" },
      { year: "1492", event: "哥伦布首次航行抵达古巴，开启西班牙殖民" },
      { year: "1511", event: "西班牙正式征服古巴，迭戈贝拉斯克斯为首任总督" },
      { year: "1519", event: "哈瓦那建城，后成为加勒比最大港口" },
      { year: "1762", event: "英国短暂占领哈瓦那（7个月），后西班牙以佛罗里达换回" },
      { year: "1791-1804", event: "海地革命导致大量法国殖民者和奴隶逃至古巴，糖业繁荣" },
      { year: "1868-1878", event: "十年战争，第一次大规模独立战争" },
      { year: "1879-1880", event: "小战争，独立运动继续" },
      { year: "1886", event: "废除奴隶制，为西半球最晚之一" },
      { year: "1895-1898", event: "何塞马蒂领导第二次独立战争" },
      { year: "1898", event: "美西战争，美国占领古巴；西班牙殖民统治结束" },
      { year: "1902", event: "古巴共和国成立，但普拉特修正案使美国保留干涉权" },
      { year: "1933", event: "中士起义，推翻马查多独裁" },
      { year: "1952", event: "巴蒂斯塔政变，建立威权统治" },
      { year: "1953", event: "卡斯特罗攻击蒙卡达兵营失败被捕" },
      { year: "1956", event: "卡斯特罗等82人乘格拉玛号游艇登陆，开始游击战" },
      { year: "1959", event: "革命胜利，巴蒂斯塔逃亡；卡斯特罗进入哈瓦那" },
      { year: "1960", event: "美国石油公司被国有化，美国实施贸易禁运" },
      { year: "1961", event: "猪湾事件失败；古巴宣布为社会主义国家" },
      { year: "1962", event: "导弹危机，美苏核对峙，世界濒临核战边缘" },
      { year: "1972", event: "加入经互会 (COMECON)，经济全面倒向苏联" },
      { year: "1980", event: "马列尔偷渡事件，约12.5万人逃往美国" },
      { year: "1991", event: "苏联解体，古巴进入特殊时期经济危机，GDP下降35%" },
      { year: "1994", event: "Maleconazo 抗议，卡斯特罗允许部分市场经济" },
      { year: "2006", event: "卡斯特罗因病将权力移交弟弟劳尔" },
      { year: "2008", event: "劳尔卡斯特罗正式就任总统，启动渐进改革" },
      { year: "2014", event: "美古关系正常化启动，奥巴马与劳尔历史性握手" },
      { year: "2017", event: "特朗普政府收紧对古政策" },
      { year: "2018", event: "迪亚斯卡内尔接任总统，为首位非卡斯特罗家族最高领导人" },
      { year: "2021", event: "7月11日全国性抗议，政府镇压逮捕数千人" },
      { year: "2024", event: "食品短缺和停电引发新一轮小规模抗议" }
    ],
    politics: {
      system: "社会主义一党制共和国",
      headOfState: "米格尔迪亚斯卡内尔",
      rulingParty: "古巴共产党 (PCC)",
      legislature: "全国人民政权代表大会",
      lastElection: "2023年",
      notes: "卡内尔为首位非卡斯特罗家族最高领导人，但面临经济改革停滞与青年外流压力。党内元老仍具影响力。",
      constitutionalHistory: "1976年宪法，2019年修宪承认私有财产和市场作用，但仍坚持共产党领导。",
      foreignRelations: "与美国关系在拜登任内略有缓和但仍紧张。俄罗斯为传统盟友。医生外交（输出医疗队）为重要软实力工具。",
      internationalOrgs: ["联合国", "不结盟运动", "美洲国家组织 (OAS，1962年被驱逐，未恢复)", "CELAC"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:4.4},{year:2016,val:0.5},{year:2017,val:1.8},{year:2018,val:2.2},{year:2019,val:-0.2},{year:2020,val:-10.9},{year:2021,val:1.3},{year:2022,val:1.8},{year:2023,val:2.0}],
      sectors: [{name:"服务业",value:72},{name:"工业",value:22},{name:"农业",value:4}],
      exports: [{name:"烟草/雪茄",value:18},{name:"镍矿",value:15},{name:"糖",value:12},{name:"医药",value:10}],
      inflation: 45.0, unemployment: 1.6,
      tradeBalance: -2500000000,
      mainPartners: ["中国", "西班牙", "德国", "俄罗斯"],
      debtToGdp: 115.0,
      fdi: 100000000,
      exchangeRate: "约24 CUP/USD (官方) 或 240+ (黑市)",
      mainCompanies: "全部为国有：Cubaniquel (镍矿), BioCubaFarma (医药), ETECSA (电信)"
    },
    society: {
      literacy: 99.8, lifeExpectancy: 78.7, urbanization: 78,
      povertyRate: 0.0, homicideRate: 4.2,
      educationExp: 12.8, healthExp: 11.8,
      ethnic: "白人 (64%), 混血 (27%), 非裔 (9%)",
      internetPenetration: 72,
      fertilityRate: 1.6,
      gii: 0.304,
      climateRisk: "高：飓风频繁（飓风艾尔玛2017年重创），海平面上升威胁沿海城市。",
      refugees: "约200万古巴裔居住在美国（主要是佛罗里达）；近年每年数万青年外流。"
    }
  },

  HTI: {
    population: 11725000, area: 27750, language: "海地克里奥尔语、法语", currency: "古德 (HTG)",
    gdp: 21000000000, gdpPerCapita: 1800, gini: 41.1, hdi: 0.552,
    overview: "海地是拉美最贫困国家，也是西半球唯一以法语和克里奥尔语为官方语言的国家。1804年通过奴隶起义独立，为世界首个黑人共和国。长期政治动荡、自然灾害频发，2021年总统遇刺后陷入治理真空。帮派控制太子港大部，联合国授权肯尼亚领导多国安全部队介入但进展缓慢。",
    history: [
      { year: "前5000", event: "泰诺人定居伊斯帕尼奥拉岛" },
      { year: "1492", event: "哥伦布首次航行抵达，建立首个美洲定居点纳维达德" },
      { year: "1496", event: "西班牙建立圣多明各城" },
      { year: "1697", event: "西班牙割让西部给法国，建立圣多曼格殖民地，成为最富裕的糖殖民地" },
      { year: "1791", event: "布克曼领导奴隶起义，海地革命开始" },
      { year: "1791-1804", event: "杜桑卢维杜尔领导革命军，先后击败西班牙、英国和法国远征军" },
      { year: "1802", event: "拿破仑派勒克莱尔远征，杜桑被骗逮捕，死于法国监狱" },
      { year: "1804", event: "德萨林宣布独立，建立海地帝国，屠杀剩余白人种植园主" },
      { year: "1825", event: "法国以军事威胁强迫海地支付1.5亿法郎赔偿金（后降至9000万），债务持续至1947年" },
      { year: "1844", event: "东部脱离海地，建立多米尼加共和国" },
      { year: "1915-1934", event: "美国军事占领，建立现代基础设施但强制劳动引发反抗" },
      { year: "1957", event: "弗朗索瓦杜瓦利埃（爸爸医生）当选总统" },
      { year: "1957-1986", event: "杜瓦利埃父子独裁统治29年，通顿马库特秘密警察杀害约3-6万人" },
      { year: "1986", event: "小杜瓦利埃被民众起义推翻，逃亡法国" },
      { year: "1990", event: "阿里斯蒂德当选首位民选总统，9个月后被军事政变推翻" },
      { year: "1994", event: "美国军事干预恢复阿里斯蒂德政权" },
      { year: "2004", event: "阿里斯蒂德再次被推翻，联合国维和部队介入" },
      { year: "2010", event: "毁灭性地震，约22-30万人死亡，太子港几乎被夷平" },
      { year: "2015-2016", event: "大选舞弊争议，莫伊兹在争议中当选" },
      { year: "2019", event: "大规模反腐败抗议，要求莫伊兹下台" },
      { year: "2021", event: "总统莫伊兹在家中遇刺身亡，据称为外国雇佣兵所为" },
      { year: "2022", event: "黑帮联盟 G9 封锁太子港燃料码头，引发人道危机" },
      { year: "2023", event: "联合国授权肯尼亚领导多国安全部队介入" },
      { year: "2024", event: "过渡委员会掌权但成效有限，帮派仍控制首都大部" }
    ],
    politics: {
      system: "半总统制共和国 (事实无政府状态)",
      headOfState: "过渡总统委员会 (集体)",
      rulingParty: "无 (各派系混战)",
      legislature: "参议院与众议院 (部分空置)",
      lastElection: "2016年 (已过期)",
      notes: "2024年过渡委员会掌权，但首都太子港被帮派控制。肯尼亚领导的多国安全部队部署缓慢。",
      constitutionalHistory: "1987年宪法，但多次被暂停或无视。2012年后修宪尝试均失败。",
      foreignRelations: "美国为最大援助国。多米尼加关闭边境并遣返海地人。联合国维和历史悠久。",
      internationalOrgs: ["联合国", "美洲国家组织 (OAS)", "加勒比共同体 (CARICOM)", "非加太集团"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:1.2},{year:2016,val:1.5},{year:2017,val:1.2},{year:2018,val:1.5},{year:2019,val:-1.7},{year:2020,val:-3.3},{year:2021,val:-1.8},{year:2022,val:-1.9},{year:2023,val:-2.0}],
      sectors: [{name:"服务业",value:55},{name:"工业",value:15},{name:"农业",value:22}],
      exports: [{name:"服装",value:35},{name:"可可",value:8},{name:"芒果",value:6},{name:"咖啡",value:5}],
      inflation: 38.7, unemployment: 14.8,
      tradeBalance: -3800000000,
      mainPartners: ["美国", "多米尼加", "加拿大", "中国"],
      debtToGdp: 28.0,
      fdi: 200000000,
      exchangeRate: "约130 HTG/USD (急剧贬值中)",
      mainCompanies: "少数私营企业，主要为外资服装厂 (maquiladoras) 和农业出口商"
    },
    society: {
      literacy: 61.7, lifeExpectancy: 64.8, urbanization: 59,
      povertyRate: 58.5, homicideRate: 10.0,
      educationExp: 2.5, healthExp: 2.3,
      ethnic: "非裔 (95%), 混血/白人 (5%)",
      internetPenetration: 38,
      fertilityRate: 2.8,
      gii: 0.635,
      climateRisk: "极高：地震、飓风、洪水、山体滑坡。森林砍伐率全球最高之一。",
      refugees: "约50万海地人居住在美国（含TPS）；每年数万人被多米尼加遣返。"
    }
  },

  DOM: {
    population: 11329000, area: 48670, language: "西班牙语", currency: "比索 (DOP)",
    gdp: 121000000000, gdpPerCapita: 10700, gini: 39.6, hdi: 0.766,
    overview: "多米尼加与海地共享伊斯帕尼奥拉岛，但发展水平显著优于邻国。经济以旅游业、离岸制造业和侨汇为支柱。近年来是加勒比增长最快经济体之一，但面临与海地边境管理和移民问题。总统阿比纳德尔2024年高票连任，主打反腐和基建。",
    history: [
      { year: "前4000", event: "泰诺人定居" },
      { year: "1492", event: "哥伦布建立首个美洲定居点拉纳维达" },
      { year: "1496", event: "建立圣多明各城，为美洲最古老持续有人居住的欧洲城市" },
      { year: "1510s", event: "建立美洲首个大教堂、医院和大学" },
      { year: "1697", event: "西班牙割让西部给法国，东部仍为西班牙殖民地" },
      { year: "1795", event: "根据巴塞尔和约，西班牙将东部割让给法国" },
      { year: "1801", event: "杜桑卢维杜尔占领东部，短暂统一岛屿" },
      { year: "1808", event: "西班牙夺回东部控制权" },
      { year: "1821", event: "独立，成立西班牙海地国" },
      { year: "1822", event: "被海地占领，持续22年" },
      { year: "1844", event: "杜阿尔特、桑切斯和梅利亚发动独立战争，建立多米尼加共和国" },
      { year: "1861-1865", event: "重新并入西班牙，后再次独立" },
      { year: "1916-1924", event: "美国军事占领" },
      { year: "1930-1961", event: "特鲁希略家族独裁统治31年，国家恐怖主义和种族清洗（针对海地移民）" },
      { year: "1961", event: "特鲁希略被暗杀" },
      { year: "1963", event: "民选总统博什被军事政变推翻" },
      { year: "1965", event: "美国再次军事干预（约翰逊总统担心另一场古巴革命）" },
      { year: "1996-2020", event: "解放党 (PLD) 连续执政24年，经济快速增长但腐败严重" },
      { year: "2020", event: "阿比纳德尔当选，承诺反腐" },
      { year: "2024", event: "阿比纳德尔以压倒性优势连任" }
    ],
    politics: {
      system: "总统制共和国",
      headOfState: "路易斯阿比纳德尔",
      rulingParty: "现代革命党 (PRM)",
      legislature: "两院制：参议院32席，众议院190席",
      lastElection: "2024年连任",
      notes: "阿比纳德尔2020年击败执政24年的 PLD 党上台，2024年高票连任，主打反腐和基建。与海地关系因边境墙和移民问题紧张。",
      constitutionalHistory: "1966年宪法，后经多次修正。2010年修宪允许总统连任。",
      foreignRelations: "美国为最重要伙伴。与海地关系复杂（边境管控、移民、贸易）。与中国无外交关系（与台湾保持邦交）。",
      internationalOrgs: ["联合国", "美洲国家组织 (OAS)", "中美洲一体化体系 (SICA)", "加勒比共同体 (观察员)"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:7.0},{year:2016,val:6.6},{year:2017,val:4.7},{year:2018,val:7.0},{year:2019,val:5.1},{year:2020,val:-6.7},{year:2021,val:12.3},{year:2022,val:4.9},{year:2023,val:2.4}],
      sectors: [{name:"服务业",value:61},{name:"工业",value:26},{name:"农业",value:5}],
      exports: [{name:"黄金",value:22},{name:"医疗器材",value:16},{name:"烟草",value:10},{name:"糖",value:7}],
      inflation: 4.2, unemployment: 5.2,
      tradeBalance: -8400000000,
      mainPartners: ["美国", "中国", "海地", "加拿大"],
      debtToGdp: 62.0,
      fdi: 4000000000,
      exchangeRate: "59 DOP/USD",
      mainCompanies: "Banco Popular (金融), Grupo Corripio (媒体), Refidomsa (炼油), Punta Cana 集团 (旅游)"
    },
    society: {
      literacy: 93.8, lifeExpectancy: 74.0, urbanization: 84,
      povertyRate: 21.8, homicideRate: 10.0,
      educationExp: 3.2, healthExp: 4.0,
      ethnic: "混血 (73%), 白人 (16%), 非裔 (11%)",
      internetPenetration: 82,
      fertilityRate: 2.3,
      gii: 0.390,
      climateRisk: "高：飓风（2017年玛利亚飓风重创）、海平面上升、干旱。",
      refugees: "约50万海地人居住在多米尼加（身份争议）；大量多米尼加人移民美国和西班牙。"
    }
  },

  COL: {
    population: 52085000, area: 1141748, language: "西班牙语 + 65种土著语言", currency: "比索 (COP)",
    gdp: 363000000000, gdpPerCapita: 7000, gini: 54.2, hdi: 0.758,
    overview: "哥伦比亚是南美第二人口大国，生物多样性全球第一。经历半个世纪内战（FARC 游击队），2016年签署和平协议获诺贝尔和平奖。经济多元化，咖啡、鲜花、石油、可卡因并存。社会极不平等，农村土地冲突持续。2022年古斯塔沃佩特罗成为首位左翼总统，推行全面和平政策和能源转型。",
    history: [
      { year: "前800-1600", event: "奇布查等印第安文明繁荣，穆伊斯卡联盟以精湛金工闻名" },
      { year: "1499", event: "阿隆索德奥赫达首次抵达哥伦比亚海岸" },
      { year: "1525", event: "西班牙建立圣玛尔塔和卡塔赫纳据点" },
      { year: "1536-1538", event: "希门内斯德克萨达征服波哥大高原，建立新格拉纳达" },
      { year: "1538", event: "波哥大建城" },
      { year: "1717", event: "新格拉纳达总督辖区建立，涵盖今哥伦比亚、委内瑞拉、厄瓜多尔和巴拿马" },
      { year: "1810", event: "波哥大爆发独立运动" },
      { year: "1819", event: "玻利瓦尔在博亚卡战役中击败西班牙军，解放新格拉纳达" },
      { year: "1821", event: "大哥伦比亚共和国成立，玻利瓦尔任总统" },
      { year: "1830", event: "大哥伦比亚解体，新格拉纳达（后称哥伦比亚）独立" },
      { year: "1851", event: "废除奴隶制" },
      { year: "1886", event: "保守党制定新宪法，中央集权化" },
      { year: "1899-1902", event: "千日战争，自由党与保守党内战，约10万人死亡" },
      { year: "1903", event: "巴拿马脱离哥伦比亚独立（美国支持），丧失地峡和运河主权" },
      { year: "1948-1958", event: "暴力时期 (La Violencia)，自由党与保守党准军事冲突，约20万人死亡" },
      { year: "1957", event: "民族阵线协议，两党轮流执政16年" },
      { year: "1964", event: "FARC 和 ELN 等左翼游击队成立" },
      { year: "1980s", event: "麦德林和卡利贩毒集团崛起，埃斯科巴尔成为世界上最富有的罪犯" },
      { year: "1991", event: "新宪法，承认多元文化、建立宪法法院" },
      { year: "2002-2010", event: "乌里韦总统民主安全政策，军事打击 FARC，安全显著改善但人权代价巨大" },
      { year: "2016", event: "桑托斯总统与 FARC 签署和平协议，获诺贝尔和平奖" },
      { year: "2017", event: "FARC 解散武装，转为政党" },
      { year: "2019", event: "全国大罢工，抗议杜克政府政策" },
      { year: "2021", event: "税制改革引发大规模抗议，政府被迫撤回方案" },
      { year: "2022", event: "古斯塔沃佩特罗当选，哥伦比亚首位左翼总统" },
      { year: "2023", event: "政府与 ELN 重启和谈；与 FARC  dissident 冲突持续" }
    ],
    politics: {
      system: "总统制共和国",
      headOfState: "古斯塔沃佩特罗",
      rulingParty: "历史公约 (Pacto Historico)",
      legislature: "两院制：参议院108席，众议院188席",
      lastElection: "2022年",
      notes: "佩特罗为前 M-19 游击队员，推行全面和平政策、能源转型和土地改革，但面临国会阻力和司法挑战。",
      constitutionalHistory: "1991年宪法为拉美最进步宪法之一，承认多元文化、建立强有力的宪法法院。",
      foreignRelations: "美国为最重要安全伙伴。与中国关系良好。与委内瑞拉关系在佩特罗任内显著改善。",
      internationalOrgs: ["联合国", "OECD", "太平洋联盟", "美洲国家组织 (OAS)", "CELAC", "NATO全球伙伴"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:3.0},{year:2016,val:2.1},{year:2017,val:1.4},{year:2018,val:2.6},{year:2019,val:3.3},{year:2020,val:-7.0},{year:2021,val:10.8},{year:2022,val:7.5},{year:2023,val:0.6}],
      sectors: [{name:"服务业",value:58},{name:"工业",value:27},{name:"农业",value:7}],
      exports: [{name:"石油",value:32},{name:"咖啡",value:8},{name:"鲜花",value:6},{name:"煤炭",value:12},{name:"黄金",value:5}],
      inflation: 6.5, unemployment: 9.8,
      tradeBalance: -8000000000,
      mainPartners: ["美国", "中国", "巴拿马", "厄瓜多尔"],
      debtToGdp: 56.0,
      fdi: 17000000000,
      exchangeRate: "3900 COP/USD",
      mainCompanies: "Ecopetrol (石油), Grupo Aval (金融), Bavaria (啤酒), Grupo Argos (水泥), ISA (能源)"
    },
    society: {
      literacy: 95.6, lifeExpectancy: 77.3, urbanization: 82,
      povertyRate: 39.3, homicideRate: 25.0,
      educationExp: 4.5, healthExp: 6.8,
      ethnic: "混血 (58%), 白人 (26%), 非裔/穆拉托 (16%)",
      internetPenetration: 75,
      fertilityRate: 1.8,
      gii: 0.381,
      climateRisk: "高：生物多样性受威胁（森林砍伐）、洪水、山体滑坡。",
      refugees: "接收约180万委内瑞拉难民（全球第二大接收国）；国内约730万人因冲突流离失所。"
    }
  },

  VEN: {
    population: 28838000, area: 916445, language: "西班牙语", currency: "玻利瓦尔 (VES)",
    gdp: 102000000000, gdpPerCapita: 3500, gini: 44.8, hdi: 0.699,
    overview: "委内瑞拉曾是世界最富裕石油国家，但查韦斯和马杜罗执政下的国有化、制裁与管理不善导致经济崩溃。恶性通胀、粮食药品短缺引发700万人外流，为现代拉美最大人道危机。反对派与执政党对峙持续，2024年马杜罗再次当选但结果不被国际承认。",
    history: [
      { year: "前10000", event: "最早人类定居" },
      { year: "前500-1500", event: "卡里尼亚、阿拉瓦克等印第安部落活跃" },
      { year: "1498", event: "哥伦布第三次航行抵达委内瑞拉海岸" },
      { year: "1499", event: "阿隆索德奥赫达探险，因看到印第安人水上村落而命名委内瑞拉（小威尼斯）" },
      { year: "1522", event: "西班牙建立科罗定居点，开始殖民" },
      { year: "1550", event: "加拉加斯建城" },
      { year: "1717", event: "并入新格拉纳达总督辖区" },
      { year: "1777", event: "成立委内瑞拉总督辖区" },
      { year: "1810", event: "加拉加斯成立最高执政委员会" },
      { year: "1811", event: "独立宣言，为第一脱离西班牙的南美国家" },
      { year: "1812", event: "地震摧毁加拉加斯，保皇派利用此事件反攻" },
      { year: "1813", event: "玻利瓦尔领导 admirable campaign，解放加拉加斯" },
      { year: "1819", event: "安哥斯图拉大会，成立大哥伦比亚" },
      { year: "1821", event: "卡拉沃沃战役，决定性地击败西班牙军" },
      { year: "1830", event: "脱离大哥伦比亚，建立独立共和国" },
      { year: "1859-1863", event: "联邦战争，中央集权派与联邦派内战" },
      { year: "1870-1888", event: "古斯曼布兰科独裁，推动现代化但腐败严重" },
      { year: "1908-1935", event: "戈麦斯独裁统治，发现石油后国家转型" },
      { year: "1945", event: "革命执政委员会推翻伊萨亚斯梅迪纳政权" },
      { year: "1948", event: "军事政变推翻罗慕洛加列戈斯（民选总统）" },
      { year: "1958", event: "推翻佩雷斯希门尼斯独裁，建立民主制度" },
      { year: "1976", event: "石油国有化" },
      { year: "1989", event: "加拉加斯暴动 (Caracazo)，IMF结构调整引发骚乱，约300-3000人死亡" },
      { year: "1992", event: "查韦斯中校发动政变失败入狱" },
      { year: "1994", event: "查韦斯获释" },
      { year: "1998", event: "查韦斯以反腐败和反建制纲领当选总统" },
      { year: "1999", event: "新宪法通过，改名委内瑞拉玻利瓦尔共和国" },
      { year: "2002", event: "短暂政变（47小时），查韦斯被军方扣押后恢复权力" },
      { year: "2004", event: "罢免公投，查韦斯获胜留任" },
      { year: "2007", event: "国有化电信和电力公司" },
      { year: "2013", event: "查韦斯去世，马杜罗继任" },
      { year: "2014", event: "学生抗议浪潮，政府镇压" },
      { year: "2015", event: "反对派赢得议会超级多数" },
      { year: "2017", event: "制宪大会选举，绕过反对派控制的国民议会" },
      { year: "2018", event: "马杜罗连任引发争议，美国等不予承认" },
      { year: "2019", event: "瓜伊多自封临时总统，获50余国承认" },
      { year: "2020-2023", event: "恶性通胀和粮食危机加剧，约700万人外流" },
      { year: "2024", event: "马杜罗再次当选，反对派拒绝承认结果，冈萨雷斯流亡西班牙" }
    ],
    politics: {
      system: "总统制共和国 (事实威权)",
      headOfState: "尼古拉斯马杜罗",
      rulingParty: "委内瑞拉统一社会主义党 (PSUV)",
      legislature: "一院制：全国代表大会 (反对派控制2015年议会但被架空)",
      lastElection: "2024年",
      notes: "马杜罗掌控军政系统，反对派领袖冈萨雷斯流亡海外。美国仍承认反对派为合法政府，但瓜伊多已失势。",
      constitutionalHistory: "1999年宪法（查韦斯主导），后经多次修正强化总统权力。制宪大会 (2017) 架空正常议会。",
      foreignRelations: "与俄罗斯、中国、伊朗、古巴关系密切。与美国断交，西方普遍不承认马杜罗政权。",
      internationalOrgs: ["联合国", "OPEC", "CELAC", "美洲玻利瓦尔联盟 (ALBA)", "美洲国家组织 (2019年被暂停)"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:-6.0},{year:2016,val:-17.0},{year:2017,val:-15.7},{year:2018,val:-19.6},{year:2019,val:-25.0},{year:2020,val:-30.0},{year:2021,val:1.0},{year:2022,val:8.0},{year:2023,val:4.0}],
      sectors: [{name:"服务业",value:52},{name:"工业",value:42},{name:"农业",value:4}],
      exports: [{name:"石油",value:95},{name:"黄金",value:3}],
      inflation: 190.0, unemployment: 6.4,
      tradeBalance: 8000000000,
      mainPartners: ["中国", "印度", "俄罗斯", "土耳其"],
      debtToGdp: 240.0,
      fdi: 500000000,
      exchangeRate: "36.5 VES/USD (官方，黑市差异巨大)",
      mainCompanies: "PDVSA (石油，国有), 绝大多数大型经济实体为国有或军方控制"
    },
    society: {
      literacy: 97.1, lifeExpectancy: 72.5, urbanization: 88,
      povertyRate: 76.0, homicideRate: 26.8,
      educationExp: 1.3, healthExp: 2.1,
      ethnic: "混血 (51%), 白人 (43%), 非裔 (3%), 印第安人 (3%)",
      internetPenetration: 72,
      fertilityRate: 2.2,
      gii: 0.466,
      climateRisk: "高：石油开采导致环境退化，奥里诺科石油带污染严重。",
      refugees: "约700万人外流（现代世界最大难民危机之一），主要前往哥伦比亚、秘鲁、厄瓜多尔、美国和西班牙。"
    }
  },

  ECU: {
    population: 18188000, area: 276841, language: "西班牙语 + 克丘亚语等", currency: "美元 (USD)",
    gdp: 121000000000, gdpPerCapita: 6700, gini: 45.4, hdi: 0.765,
    overview: "厄瓜多尔国名意为赤道共和国，经济高度依赖石油出口。2000年因金融危机美元化。科雷亚总统 (2007-2017) 推动左翼改革和反新自由主义政策，但之后保守派重掌政权。近年因毒品贩运路线改变，暴力犯罪急剧上升。2023年最年轻总统诺沃亚以治安为号召当选，2025年公投强化打击犯罪。",
    history: [
      { year: "前3500", event: "最早人类定居" },
      { year: "前800-1500", event: "卡拉文化、Tolita 文化繁荣，精湛金工和陶瓷" },
      { year: "1460s", event: "印加帝国征服北部高地" },
      { year: "1533", event: "皮萨罗征服基多，印加帝国覆灭" },
      { year: "1534", event: "西班牙建立基多城" },
      { year: "1563", event: "建立基多皇家审问院，为秘鲁总督辖区下辖" },
      { year: "1717", event: "划入新格拉纳达总督辖区" },
      { year: "1740", event: "建立基多学派，巴洛克艺术繁荣" },
      { year: "1809", event: "基多首次独立尝试（第一个呼喊独立的城市）" },
      { year: "1822", event: "苏克雷在皮钦查战役中击败西班牙军，玻利瓦尔解放厄瓜多尔" },
      { year: "1822-1830", event: "大哥伦比亚成员国" },
      { year: "1830", event: "脱离大哥伦比亚独立" },
      { year: "1830-1845", event: "大哥伦比亚解体后不稳定时期" },
      { year: "1845-1860", event: "加西亚莫雷诺保守派独裁，建立神权政治" },
      { year: "1895", event: "自由派革命，埃洛伊阿尔法罗建立世俗国家" },
      { year: "1912", event: "阿尔法罗被暗杀" },
      { year: "1925-1948", event: "香蕉共和国时代，美国联合果品公司主导经济" },
      { year: "1941", event: "与秘鲁边境战争，丧失南部大片领土" },
      { year: "1944", event: "五月革命，推翻阿罗约总统" },
      { year: "1948", event: "香蕉种植园工人大罢工和屠杀" },
      { year: "1963", event: "军事政变" },
      { year: "1972-1979", event: "军人执政，石油繁荣" },
      { year: "1979", event: "恢复民主" },
      { year: "1995-1998", event: "与秘鲁塞内帕战争" },
      { year: "1997", event: "布卡拉姆总统因精神失常被议会罢免（仅执政6个月）" },
      { year: "1998-1999", event: "马瓦德总统因银行危机下台，诺沃亚接任" },
      { year: "2000", event: "金融危机后全面美元化" },
      { year: "2006", event: "科雷亚当选，开启公民革命" },
      { year: "2008", event: "新宪法通过，承认自然权利" },
      { year: "2013", event: "科雷亚连任，但支持率开始下滑" },
      { year: "2017", event: "莫雷诺当选，与科雷亚决裂，右转" },
      { year: "2019", event: "抗议浪潮，政府被迫放弃燃料补贴削减" },
      { year: "2021", event: "拉索当选总统" },
      { year: "2023", event: "总统候选人比利亚维森西奥遇刺，诺沃亚意外当选" },
      { year: "2024", event: "诺沃亚宣布进入内部武装冲突状态，打击贩毒集团" },
      { year: "2025", event: "公投通过强化治安措施" }
    ],
    politics: {
      system: "总统制共和国",
      headOfState: "丹尼尔诺沃亚",
      rulingParty: "国家民主行动 (ADN)",
      legislature: "一院制：国民议会137席",
      lastElection: "2023年",
      notes: "诺沃亚年仅35岁成为史上最年轻总统，香蕉大亨之子。面对犯罪飙升和议会碎片化挑战，2025年举行公投强化治安。",
      constitutionalHistory: "2008年宪法（科雷亚主导），承认自然权利和多元文化，但2018年后保守派试图修改。",
      foreignRelations: "美国为重要伙伴（安全和贸易）。与中国关系密切（石油换贷款）。与邻国关系良好。",
      internationalOrgs: ["联合国", "OPEC", "太平洋联盟", "美洲国家组织 (OAS)", "CELAC"]
    },
    economy: {
      gdpGrowth: [{year:2015,val:0.1},{year:2016,val:-1.2},{year:2017,val:2.4},{year:2018,val:1.3},{year:2019,val:0.0},{year:2020,val:-7.8},{year:2021,val:4.2},{year:2022,val:2.9},{year:2023,val:2.4}],
      sectors: [{name:"服务业",value:54},{name:"工业",value:33},{name:"农业",value:9}],
      exports: [{name:"石油",value:38},{name:"香蕉",value:10},{name:"虾",value:8},{name:"可可",value:7},{name:"鲜花",value:6}],
      inflation: 2.7, unemployment: 3.5,
      tradeBalance: 1800000000,
      mainPartners: ["美国", "中国", "巴拿马", "秘鲁"],
      debtToGdp: 53.0,
      fdi: 1300000000,
      exchangeRate: "美元化 (自2000年起)",
      mainCompanies: "Petroecuador (石油，国有), Banco Pichincha (金融), Noboa 集团 (香蕉)"
    },
    society: {
      literacy: 93.3, lifeExpectancy: 77.4, urbanization: 65,
      povertyRate: 27.0, homicideRate: 27.0,
      educationExp: 4.0, healthExp: 4.6,
      ethnic: "混血 (71%), 印第安人 (7%), 白人 (6%), 非裔 (4%), 其他 (12%)",
      internetPenetration: 75,
      fertilityRate: 2.0,
      gii: 0.368,
      climateRisk: "高：加拉帕戈斯群岛生态系统脆弱，亚马逊森林砍伐，火山活动（科托帕希等）。",
      refugees: "接收约50万委内瑞拉难民；本国移民主要前往美国和西班牙。"
    }
  },
  PER: {"population": 34352000, "area": 1285216, "language": "西班牙语 + 克丘亚语 + 艾马拉语", "currency": "索尔 (PEN)", "gdp": 275000000000, "gdpPerCapita": 8000, "gini": 42.8, "hdi": 0.762, "overview": "秘鲁是印加帝国发源地，拥有马丘比丘等世界遗产。经济依赖矿业（铜、金、银），但资源分配严重不均。2016-2022年经历六位总统和两次宪政危机，政治极度不稳定。藤森家族左右政坛数十年。", "history": [{"year": "前1200-1533", "event": "印加帝国崛起，领土从哥伦比亚延伸至智利，建立庞大道路系统和中央集权行政"}, {"year": "前1438", "event": "帕查库特克即位，开启印加帝国大扩张"}, {"year": "1532", "event": "皮萨罗在卡哈马卡俘虏印加皇帝阿塔瓦尔帕"}, {"year": "1533", "event": "阿塔瓦尔帕被处决，印加帝国覆灭"}, {"year": "1535", "event": "皮萨罗建立利马城"}, {"year": "1542", "event": "西班牙建立秘鲁总督辖区，管辖整个南美大部"}, {"year": "1572", "event": "最后一位印加抵抗领袖图帕克阿马鲁被处决"}, {"year": "1780-1781", "event": "图帕克阿马鲁二世起义，约10万人死亡"}, {"year": "1821", "event": "圣马丁宣布秘鲁独立"}, {"year": "1824", "event": "阿亚库乔战役，决定性地击败西班牙军"}, {"year": "1836-1839", "event": "秘鲁-玻利维亚邦联，后被智利和阿根廷联合瓦解"}, {"year": "1845-1862", "event": "拉蒙卡斯蒂利亚总统，鸟粪繁荣推动现代化"}, {"year": "1879-1883", "event": "太平洋战争，秘鲁和玻利维亚战败，秘鲁割让塔拉帕卡给智利"}, {"year": "1895", "event": "尼古拉斯德皮埃罗拉重新统一国家"}, {"year": "1908-1912", "event": "莱吉亚总统，推动基础设施建设"}, {"year": "1924", "event": "阿普拉党 (APRA) 成立，为拉美最早的群众政党之一"}, {"year": "1930", "event": "桑切斯塞罗军事政变"}, {"year": "1948", "event": "奥德里亚军事政变"}, {"year": "1963-1968", "event": "贝朗德特里民选执政，推动土地改革"}, {"year": "1968", "event": "贝拉斯科将军军事政变，推行激进改革"}, {"year": "1980", "event": "贝朗德特里再次当选，恢复民主"}, {"year": "1980-2000", "event": "光辉道路 (Shining Path) 和图帕克阿马鲁革命运动 (MRTA) 游击队与政府对抗，约7万人死亡"}, {"year": "1985", "event": "加西亚当选，推行民粹主义政策，导致恶性通胀"}, {"year": "1990", "event": "藤森谦也当选总统"}, {"year": "1992", "event": "藤森自我政变，解散国会，逮捕光辉道路领导人阿维马埃尔古斯曼"}, {"year": "1995", "event": "藤森与厄瓜多尔签署和平条约"}, {"year": "2000", "event": "藤森因腐败和贿选丑闻辞职，流亡日本"}, {"year": "2001-2006", "event": "托莱多总统，推动真相与和解委员会"}, {"year": "2006-2011", "event": "加西亚再次执政（第二次任期）"}, {"year": "2011-2016", "event": "奥良塔乌马拉 (Humala) 执政，温和左翼"}, {"year": "2016", "event": "库琴斯基当选，但卷入奥德布雷希特腐败案"}, {"year": "2018", "event": "比斯卡拉总统因宪法改革与国会冲突"}, {"year": "2020", "event": "比斯卡拉被国会弹劾罢免，梅里诺代理总统5天后因大规模抗议辞职"}, {"year": "2021", "event": "卡斯蒂略当选，为首位农村教师和左翼总统"}, {"year": "2022", "event": "卡斯蒂略试图解散国会反被罢免入狱，副总统博卢阿特继任"}, {"year": "2022-2024", "event": "持续抗议要求博卢阿特辞职和提前大选"}], "politics": {"system": "总统制共和国", "headOfState": "迪娜博卢阿特", "rulingParty": "无 (独立，原为秘鲁自由党)", "legislature": "一院制：国会130席", "lastElection": "2021年 (副总统继任)", "notes": "博卢阿特为卡斯蒂略副总统，继任后面临合法性争议和持续抗议，支持率极低。", "constitutionalHistory": "1993年宪法（藤森主导），历经多次修正。总统不可连任，但可隔届参选。", "foreignRelations": "中国为最大贸易伙伴（矿产）。美国为安全伙伴。与智利关系因边界问题有摩擦。", "internationalOrgs": ["联合国", "APEC", "太平洋联盟", "美洲国家组织 (OAS)", "CELAC"]}, "economy": {"gdpGrowth": [{"year": 2015, "val": 3.3}, {"year": 2016, "val": 4.0}, {"year": 2017, "val": 2.5}, {"year": 2018, "val": 4.0}, {"year": 2019, "val": 2.2}, {"year": 2020, "val": -11.0}, {"year": 2021, "val": 13.4}, {"year": 2022, "val": 2.7}, {"year": 2023, "val": 0.6}], "sectors": [{"name": "服务业", "value": 53}, {"name": "工业", "value": 31}, {"name": "农业", "value": 7}], "exports": [{"name": "铜矿", "value": 28}, {"name": "黄金", "value": 14}, {"name": "锌", "value": 6}, {"name": "天然气", "value": 5}], "inflation": 3.5, "unemployment": 6.8, "tradeBalance": 14000000000, "mainPartners": ["中国", "美国", "瑞士", "加拿大"], "debtToGdp": 33.0, "fdi": 8000000000, "exchangeRate": "3.7 PEN/USD", "mainCompanies": "Southern Copper (铜矿), Buenaventura (金矿), Credicorp (金融), Alicorp (食品)"}, "society": {"literacy": 94.5, "lifeExpectancy": 76.7, "urbanization": 79, "povertyRate": 27.5, "homicideRate": 8.3, "educationExp": 3.6, "healthExp": 5.2, "ethnic": "印第安人/混血 (60%), 白人 (15%), 非裔 (3%), 其他 (22%)", "internetPenetration": 74, "fertilityRate": 2.0, "gii": 0.369, "climateRisk": "高：亚马逊森林砍伐（全球第四）、冰川融化（安第斯）、地震和厄尔尼诺现象。", "refugees": "接收约150万委内瑞拉难民；本国移民前往美国、智利和西班牙。"}},
  BRA: {"population": 216400000, "area": 8515767, "language": "葡萄牙语", "currency": "雷亚尔 (BRL)", "gdp": 2174000000000, "gdpPerCapita": 10000, "gini": 53.4, "hdi": 0.76, "overview": "巴西是拉美最大国家和经济体，全球第五大领土和人口国。拥有亚马逊雨林和全球最大的葡萄牙语人口。工业基础雄厚，农业全球领先。近年政治极化严重，博索纳罗与卢拉两大阵营对立。", "history": [{"year": "前11000", "event": "最早人类定居，形成数千个部落"}, {"year": "1500", "event": "卡布拉尔抵达，葡萄牙建立殖民地"}, {"year": "1549", "event": "建立萨尔瓦多总督府，统一殖民管理"}, {"year": "1600s-1700s", "event": "蔗糖周期和黄金周期，大量非洲奴隶被贩运至巴西（约400万）"}, {"year": "1808", "event": "葡萄牙王室迁至里约热内卢，为唯一迁都至殖民地的欧洲王室"}, {"year": "1822", "event": "佩德罗一世宣布独立，建立巴西帝国"}, {"year": "1864-1870", "event": "三国同盟战争（巴拉圭战争）"}, {"year": "1888", "event": "废除奴隶制，为西方世界最晚"}, {"year": "1889", "event": "丰塞卡将军发动政变，建立共和国"}, {"year": "1930-1945", "event": "瓦加斯独裁统治，推行民粹主义和工业化"}, {"year": "1956-1961", "event": "库比契克总统，建设新首都巴西利亚"}, {"year": "1960", "event": "首都从里约热内卢迁至巴西利亚"}, {"year": "1964-1985", "event": "军事独裁统治，打压反对派，经济快速增长但伴随严重人权侵犯"}, {"year": "1985", "event": "恢复文人政府"}, {"year": "1988", "event": "公民宪法颁布，被称为世界上最进步的宪法之一"}, {"year": "2003-2010", "event": "卢拉执政，社会项目使数千万人脱贫"}, {"year": "2014", "event": "世界杯举办，但同期爆发大规模反腐败抗议"}, {"year": "2016", "event": "罗塞夫总统被弹劾下台"}, {"year": "2018", "event": "博索纳罗当选，极右翼首次掌权"}, {"year": "2020", "event": "COVID导致博索纳罗支持率下降，亚马逊森林砍伐达到峰值"}, {"year": "2022", "event": "卢拉以微弱优势击败博索纳罗回归"}, {"year": "2023", "event": "博索纳罗支持者冲击国会、最高法院和总统府（巴西版国会山事件）"}], "politics": {"system": "联邦总统制共和国", "headOfState": "路易斯伊纳西奥卢拉达席尔瓦", "rulingParty": "劳工党 (PT)", "legislature": "两院制：参议院81席，众议院513席", "lastElection": "2022年", "notes": "卢拉2022年击败博索纳罗回归，以微弱优势胜选。执政联盟需面对极右翼反对党和国会碎片化。", "constitutionalHistory": "1988年公民宪法为巴西民主基石，保障广泛社会权利。但修正案频繁，2017年后劳动改革削弱工人保护。", "foreignRelations": "南方共同市场 (Mercosur) 核心成员。与美国关系在博索纳罗时期紧密、卢拉时期较平衡。与中国为最大贸易伙伴。", "internationalOrgs": ["联合国", "G20", "金砖国家", "Mercosur", "OAS", "CELAC", "OECD候选国"]}, "economy": {"gdpGrowth": [{"year": 2015, "val": -3.5}, {"year": 2016, "val": -3.3}, {"year": 2017, "val": 1.3}, {"year": 2018, "val": 1.8}, {"year": 2019, "val": 1.2}, {"year": 2020, "val": -3.9}, {"year": 2021, "val": 4.8}, {"year": 2022, "val": 3.0}, {"year": 2023, "val": 2.9}], "sectors": [{"name": "服务业", "value": 58}, {"name": "工业", "value": 21}, {"name": "农业", "value": 6}], "exports": [{"name": "大豆", "value": 18}, {"name": "石油", "value": 14}, {"name": "铁矿石", "value": 12}, {"name": "糖", "value": 5}, {"name": "肉类", "value": 6}], "inflation": 4.6, "unemployment": 7.4, "tradeBalance": 88000000000, "mainPartners": ["中国", "美国", "阿根廷", "荷兰"], "debtToGdp": 74.0, "fdi": 64000000000, "exchangeRate": "4.9 BRL/USD", "mainCompanies": "Petrobras (石油), Vale (矿业), Itau Unibanco (金融), JBS (肉类), Ambev (饮料)"}, "society": {"literacy": 93.2, "lifeExpectancy": 76.0, "urbanization": 88, "povertyRate": 24.3, "homicideRate": 22.4, "educationExp": 6.0, "healthExp": 9.9, "ethnic": "混血 (43%), 白人 (47%), 非裔 (8%), 印第安人 (1%), 其他 (1%)", "internetPenetration": 84, "fertilityRate": 1.6, "gii": 0.391, "climateRisk": "极高：亚马逊森林砍伐（全球最严重）、 Pantanal 湿地火灾、极端天气事件增加。", "refugees": "接收约50万委内瑞拉难民；本国移民前往美国、日本和欧洲。"}},
  BOL: {"population": 12388000, "area": 1098581, "language": "西班牙语 + 克丘亚语 + 艾马拉语", "currency": "玻利维亚诺 (BOB)", "gdp": 48000000000, "gdpPerCapita": 3900, "gini": 42.2, "hdi": 0.692, "overview": "玻利维亚是南美最贫穷国家之一，但拥有世界最大锂储量。2005年莫拉莱斯成为首位印第安人总统，推行资源国有化和反新自由主义政策。2019年因选举争议辞职流亡，2020年MAS党重新执政。", "history": [{"year": "前600-1000", "event": "蒂亚瓦纳科文明繁荣"}, {"year": "1438-1533", "event": "印加帝国征服玻利维亚高原地区"}, {"year": "1538", "event": "西班牙建立殖民统治，波托西银矿为世界最大"}, {"year": "1545", "event": "波托西银矿发现，成为西班牙帝国财富核心"}, {"year": "1780-1781", "event": "图帕克阿马鲁二世起义波及玻利维亚高原"}, {"year": "1809", "event": "丘基萨卡（今苏克雷）和拉巴斯爆发独立运动"}, {"year": "1825", "event": "玻利瓦尔解放，以他命名独立"}, {"year": "1836-1839", "event": "秘鲁-玻利维亚邦联"}, {"year": "1879-1883", "event": "太平洋战争，丧失出海口给智利，成为内陆国"}, {"year": "1899", "event": "联邦主义革命，自由派掌权"}, {"year": "1932-1935", "event": "查科战争，与巴拉圭争夺石油地带"}, {"year": "1952", "event": "民族革命，实施土地改革和矿产国有化，赋予印第安人投票权"}, {"year": "1964-1982", "event": "军人反复政变和执政"}, {"year": "1985", "event": "新自由主义改革，关闭国有矿企 COMIBOL"}, {"year": "2000", "event": "科恰班巴水战，民众反对自来水私有化"}, {"year": "2003", "event": "天然气战争，民众抗议天然气出口，桑切斯总统辞职"}, {"year": "2005", "event": "莫拉莱斯当选首位印第安人总统"}, {"year": "2006-2009", "event": "制宪大会、新宪法、国有化天然气和电信"}, {"year": "2019", "event": "选举争议引发抗议，莫拉莱斯辞职流亡阿根廷（后至墨西哥）"}, {"year": "2020", "event": "阿尔塞当选，MAS党重新执政"}, {"year": "2024", "event": "未遂政变，将军苏尼加被逮捕"}], "politics": {"system": "总统制共和国", "headOfState": "路易斯阿尔塞", "rulingParty": "争取社会主义运动 (MAS)", "legislature": "两院制：参议院36席，众议院130席", "lastElection": "2020年", "notes": "阿尔塞为莫拉莱斯经济部长出身，试图平衡延续社会项目与寻求外国投资，但党内分裂严重。", "constitutionalHistory": "2009年宪法（莫拉莱斯主导），承认多元民族国家性质，赋予印第安人自治权。", "foreignRelations": "与美国关系紧张。与俄罗斯中国关系密切。因出海口争端与智利关系长期冷淡。", "internationalOrgs": ["联合国", "Mercosur", "美洲国家组织 (OAS，2012年曾退出)", "CELAC", "不结盟运动"]}, "economy": {"gdpGrowth": [{"year": 2015, "val": 4.9}, {"year": 2016, "val": 4.3}, {"year": 2017, "val": 4.2}, {"year": 2018, "val": 4.2}, {"year": 2019, "val": 2.2}, {"year": 2020, "val": -8.7}, {"year": 2021, "val": 6.1}, {"year": 2022, "val": 3.6}, {"year": 2023, "val": 2.5}], "sectors": [{"name": "服务业", "value": 48}, {"name": "工业", "value": 32}, {"name": "农业", "value": 12}], "exports": [{"name": "天然气", "value": 30}, {"name": "矿产(锌/银/金)", "value": 25}, {"name": "大豆", "value": 12}, {"name": "锂(潜力)", "value": 0}], "inflation": 2.9, "unemployment": 3.5, "tradeBalance": -600000000, "mainPartners": ["阿根廷", "巴西", "印度", "中国"], "debtToGdp": 68.0, "fdi": 300000000, "exchangeRate": "6.9 BOB/USD (盯住美元)", "mainCompanies": "YPFB (石油天然气，国有), COMIBOL (矿业，国有), Banco Union (国有)"}, "society": {"literacy": 94.5, "lifeExpectancy": 71.5, "urbanization": 72, "povertyRate": 36.3, "homicideRate": 5.0, "educationExp": 6.8, "healthExp": 6.0, "ethnic": "印第安人/混血 (68%), 白人 (5%), 乔洛 (混血, 27%)", "internetPenetration": 60, "fertilityRate": 2.5, "gii": 0.383, "climateRisk": "高：安第斯冰川融化、高原干旱、亚马逊森林砍伐。", "refugees": "少量接收邻国难民；本国人口外流至阿根廷和西班牙。"}},
  PRY: {"population": 6861000, "area": 406752, "language": "西班牙语 + 瓜拉尼语", "currency": "瓜拉尼 (PYG)", "gdp": 47000000000, "gdpPerCapita": 6900, "gini": 43.5, "hdi": 0.731, "overview": "巴拉圭是拉美唯一的双语国家（西班牙语和瓜拉尼语皆为官方语言）。拥有世界第三大水电站伊泰普水电站（与巴西共建）。经济依赖农业（大豆、牛肉），但财富高度集中于少数家族手中。", "history": [{"year": "前1000", "event": "瓜拉尼人定居"}, {"year": "1537", "event": "西班牙建立亚松森，为拉普拉塔地区首个定居点"}, {"year": "1609-1767", "event": "耶稣会在查科地区建立传教区（ reductions ），保护印第安人免于奴役"}, {"year": "1776", "event": "划入拉普拉塔总督辖区"}, {"year": "1811", "event": "独立"}, {"year": "1814-1840", "event": "弗朗西亚博士独裁统治，闭关锁国"}, {"year": "1844-1862", "event": "卡洛斯安东尼奥洛佩斯总统，对外开放和现代化"}, {"year": "1864-1870", "event": "三国同盟战争，巴拉圭对抗巴西阿根廷乌拉圭，丧失60%人口和大量领土"}, {"year": "1870-1904", "event": "重建时期，人口从约50万降至22万"}, {"year": "1932-1935", "event": "查科战争，与玻利维亚争夺石油地带"}, {"year": "1936", "event": "二月革命，推翻自由党政府"}, {"year": "1940", "event": "莫里尼戈独裁统治"}, {"year": "1954", "event": "斯特罗斯纳将军发动政变"}, {"year": "1954-1989", "event": "斯特罗斯纳独裁统治35年，为美洲最长军事独裁之一"}, {"year": "1989", "event": "罗德里格斯将军发动政变，推翻斯特罗斯纳"}, {"year": "1992", "event": "新宪法，承认瓜拉尼语为官方语言"}, {"year": "1996", "event": "奥维多将军未遂政变"}, {"year": "2000", "event": "冈萨雷斯马基总统因腐败丑闻辞职"}, {"year": "2008", "event": "卢戈主教当选总统，结束红党61年执政"}, {"year": "2012", "event": "卢戈总统被议会闪电弹劾罢免（南美首次合法政变）"}, {"year": "2013", "event": "卡特斯当选，红党重返执政"}, {"year": "2018", "event": "阿夫多当选，延续红党执政"}, {"year": "2023", "event": "圣地亚哥培尼亚当选，红党继续执政"}], "politics": {"system": "总统制共和国", "headOfState": "圣地亚哥培尼亚", "rulingParty": "红党 (ANR-Colorado)", "legislature": "两院制：参议院45席，众议院80席", "lastElection": "2023年", "notes": "培尼亚代表红党参选，但背后实权人物为前Cartes总统。红党已执政近70年（除2008-2013）。", "constitutionalHistory": "1992年宪法承认瓜拉尼语为官方语言，为拉美最独特宪政安排之一。", "foreignRelations": "巴西为最重要伙伴（伊泰普水电站）。与台湾保持邦交（仅余少数之一）。", "internationalOrgs": ["联合国", "Mercosur", "美洲国家组织 (OAS)", "CELAC"]}, "economy": {"gdpGrowth": [{"year": 2015, "val": 3.0}, {"year": 2016, "val": 4.3}, {"year": 2017, "val": 4.8}, {"year": 2018, "val": 3.0}, {"year": 2019, "val": 0.0}, {"year": 2020, "val": -0.8}, {"year": 2021, "val": 4.0}, {"year": 2022, "val": 0.1}, {"year": 2023, "val": 4.7}], "sectors": [{"name": "服务业", "value": 51}, {"name": "工业", "value": 26}, {"name": "农业", "value": 13}], "exports": [{"name": "大豆", "value": 28}, {"name": "牛肉", "value": 18}, {"name": "电力", "value": 12}, {"name": "谷物", "value": 10}], "inflation": 4.6, "unemployment": 5.6, "tradeBalance": 800000000, "mainPartners": ["巴西", "阿根廷", "智利", "美国"], "debtToGdp": 38.0, "fdi": 400000000, "exchangeRate": "7300 PYG/USD", "mainCompanies": "Itaipu Binacional (水电，与巴西合资), Grupo Cartes (烟草/银行), Basa (金融)"}, "society": {"literacy": 94.0, "lifeExpectancy": 74.9, "urbanization": 63, "povertyRate": 24.7, "homicideRate": 6.5, "educationExp": 3.3, "healthExp": 4.5, "ethnic": "混血 (95%), 白人 (3%), 印第安人 (2%)", "internetPenetration": 78, "fertilityRate": 2.3, "gii": 0.394, "climateRisk": "高：极端天气事件、干旱（大豆产区）、洪水。", "refugees": "接收少量邻国移民；本国人口外流至阿根廷和西班牙。"}},
  CHL: {"population": 19629000, "area": 756102, "language": "西班牙语", "currency": "比索 (CLP)", "gdp": 358000000000, "gdpPerCapita": 18300, "gini": 44.9, "hdi": 0.86, "overview": "智利是拉美发展水平最高国家，HDI和人均GDP居首。皮诺切特独裁（1973-1990）后推行新自由主义改革，成为市场开放典范。2019年社会爆发 estallido social 抗议，推动新宪法起草（2022年被否决）。", "history": [{"year": "前10000", "event": "最早人类定居"}, {"year": "前500-1450", "event": "Mapuche 等印第安部落活跃，从未被印加帝国完全征服"}, {"year": "1520", "event": "麦哲伦首次航行通过智利海峡"}, {"year": "1541", "event": "圣地亚哥建城，西班牙征服开始"}, {"year": "1553", "event": "马普切领袖劳塔罗击败西班牙军，杀死征服者巴尔迪维亚"}, {"year": "1600s-1700s", "event": "阿劳卡尼亚战争持续，西班牙未能征服马普切人"}, {"year": "1810", "event": "圣地亚哥成立执政委员会"}, {"year": "1814", "event": "兰卡瓜战役，西班牙军击败起义军"}, {"year": "1817", "event": "查卡布科战役，圣马丁和奥希金斯击败西班牙军"}, {"year": "1818", "event": "奥希金斯领导独立"}, {"year": "1830-1837", "event": "迭戈波塔莱斯独裁，建立保守共和国"}, {"year": "1879-1883", "event": "太平洋战争，击败秘鲁玻利维亚夺取硝石矿"}, {"year": "1891", "event": "内战，国会派击败巴尔马塞达总统"}, {"year": "1920s-1930s", "event": "社会动荡和工人运动兴起"}, {"year": "1932", "event": "海军抗议（Seguro Obrero 屠杀）"}, {"year": "1970", "event": "阿连德通过选举成为首位马克思主义总统"}, {"year": "1973", "event": "皮诺切特军事政变，阿连德殉职，开启17年独裁"}, {"year": "1980", "event": "新宪法公投（有争议通过）"}, {"year": "1988", "event": "公投否决皮诺切特连任，恢复民主进程启动"}, {"year": "1990", "event": "恢复民主，建立执政联盟"}, {"year": "2010", "event": "加入 OECD，成为首个南美成员国"}, {"year": "2010", "event": "33名矿工被困69天后全部获救，引发全球关注"}, {"year": "2019", "event": "全国性社会抗议，地铁涨价为导火索"}, {"year": "2020", "event": "公投通过起草新宪法"}, {"year": "2021", "event": "博里奇当选，35岁成为史上最年轻总统"}, {"year": "2022", "event": "新宪法草案在公投中被否决（62%反对）"}, {"year": "2023", "event": "再次启动新宪法起草进程"}], "politics": {"system": "总统制共和国", "headOfState": "加夫列尔博里奇", "rulingParty": "广泛阵线 (FA)", "legislature": "两院制：参议院50席，众议院155席", "lastElection": "2021年", "notes": "博里奇为35岁当选的最年轻总统，代表学生运动和左翼联盟，推动养老金改革和税制改革。", "constitutionalHistory": "1980年宪法（皮诺切特主导），历经多次修正。2022年新宪法草案被否决，2023年再次启动制宪。", "foreignRelations": "美国为重要安全伙伴。与中国为最大贸易伙伴（铜矿）。与邻国关系总体良好。", "internationalOrgs": ["联合国", "OECD", "APEC", "太平洋联盟", "Mercosur", "美洲国家组织 (OAS)"]}, "economy": {"gdpGrowth": [{"year": 2015, "val": 2.3}, {"year": 2016, "val": 1.7}, {"year": 2017, "val": 1.3}, {"year": 2018, "val": 4.0}, {"year": 2019, "val": 0.9}, {"year": 2020, "val": -5.8}, {"year": 2021, "val": 11.7}, {"year": 2022, "val": 2.4}, {"year": 2023, "val": 0.2}], "sectors": [{"name": "服务业", "value": 60}, {"name": "工业", "value": 34}, {"name": "农业", "value": 4}], "exports": [{"name": "铜矿", "value": 48}, {"name": "水果(车厘子/葡萄)", "value": 10}, {"name": "林产品", "value": 8}, {"name": "三文鱼", "value": 6}, {"name": "葡萄酒", "value": 2}], "inflation": 7.6, "unemployment": 8.4, "tradeBalance": 5000000000, "mainPartners": ["中国", "美国", "日本", "巴西"], "debtToGdp": 34.0, "fdi": 15000000000, "exchangeRate": "860 CLP/USD", "mainCompanies": "Codelco (铜矿，国有), SQM (锂矿), Falabella (零售), LATAM Airlines (航空), CMPC (纸浆)"}, "society": {"literacy": 97.0, "lifeExpectancy": 80.4, "urbanization": 88, "povertyRate": 6.5, "homicideRate": 4.8, "educationExp": 5.4, "healthExp": 9.3, "ethnic": "白人/混血 (89%), 印第安人 (10%), 其他 (1%)", "internetPenetration": 92, "fertilityRate": 1.7, "gii": 0.247, "climateRisk": "极高：干旱（北部）、冰川融化（安第斯）、森林火灾、地震和海啸。", "refugees": "接收约70万委内瑞拉难民；本国移民前往美国、澳大利亚和瑞典。"}},
  ARG: {"population": 46023000, "area": 2780400, "language": "西班牙语", "currency": "比索 (ARS)", "gdp": 632000000000, "gdpPerCapita": 13700, "gini": 42.3, "hdi": 0.842, "overview": "阿根廷曾是世界最富裕国家之一（20世纪初），但长期受债务危机、高通胀和民粹主义困扰。2023年哈维尔米莱当选，推行激进的自由主义和美元化主张，大幅削减政府部门和补贴。社会持续动荡。", "history": [{"year": "前10000", "event": "最早人类定居"}, {"year": "1516", "event": "西班牙探险队抵达拉普拉塔"}, {"year": "1536", "event": "建立布宜诺斯艾利斯（第一次，后被印第安人摧毁）"}, {"year": "1580", "event": "加拉伊重建布宜诺斯艾利斯"}, {"year": "1776", "event": "建立拉普拉塔总督辖区"}, {"year": "1810", "event": "五月革命，推翻西班牙总督"}, {"year": "1816", "event": "独立宣言"}, {"year": "1816-1880", "event": "内战时期，联邦派与集权派对抗"}, {"year": "1860-1930", "event": "繁荣时期，成为世界最大粮食出口国和欧洲移民热门目的地"}, {"year": "1880-1916", "event": "保守派寡头统治，'80年代一代'推动现代化"}, {"year": "1912", "event": "实施男性普选"}, {"year": "1916-1930", "event": "激进公民联盟执政，伊里戈延推动社会改革"}, {"year": "1930", "event": "乌里布鲁军事政变，开启军事干政时代"}, {"year": "1943", "event": "军事政变，庇隆进入权力核心"}, {"year": "1946-1955", "event": "庇隆首次执政，建立民粹主义模式，赋予劳工广泛权利"}, {"year": "1955", "event": "海军轰炸五月广场，推翻庇隆（解放革命）"}, {"year": "1955-1958", "event": "洛纳迪和阿拉布鲁塞军事执政"}, {"year": "1966", "event": "翁加尼亚政变（阿根廷革命），禁止政党活动"}, {"year": "1973", "event": "庇隆结束流亡回归，再次当选总统"}, {"year": "1974", "event": "庇隆去世，妻子伊莎贝尔继任"}, {"year": "1976-1983", "event": "肮脏战争，军政府镇压左翼，约3万人失踪"}, {"year": "1982", "event": "马岛战争，阿根廷战败"}, {"year": "1983", "event": "恢复民主，阿方辛当选"}, {"year": "1989", "event": "梅内姆当选，推行新自由主义改革"}, {"year": "1991", "event": "货币局制度，比索与美元1:1挂钩"}, {"year": "2001-2002", "event": "严重经济危机，一周内五位总统更替"}, {"year": "2003-2007", "event": "基什内尔总统，摆脱危机，恢复增长"}, {"year": "2007-2015", "event": "克里斯蒂娜基什内尔执政，民粹主义回归"}, {"year": "2015-2019", "event": "马克里总统，推行新自由主义，但未能解决债务问题"}, {"year": "2018", "event": "与国际货币基金组织签署570亿美元救助协议"}, {"year": "2019-2023", "event": "费尔南德斯执政，COVID和经济危机叠加"}, {"year": "2023", "event": "米莱当选总统，推行休克疗法"}, {"year": "2024", "event": "比索大幅贬值，通胀率超过100%，大幅削减政府开支"}], "politics": {"system": "联邦总统制共和国", "headOfState": "哈维尔米莱", "rulingParty": "自由前进 (LLA)", "legislature": "两院制：参议院72席，众议院257席", "lastElection": "2023年", "notes": "米莱为经济学家和电视评论员出身，主张废除央行、全面美元化、削减公共开支。国会少数派，依赖地方州长支持。", "constitutionalHistory": "1853年宪法，历经多次修正。1994年修宪允许总统连任一次。", "foreignRelations": "美国为传统盟友。与中国关系复杂（大豆贸易重要但米莱政府持批评态度）。与英国因马岛争端断交。", "internationalOrgs": ["联合国", "G20", "Mercosur", "美洲国家组织 (OAS)", "CELAC"]}, "economy": {"gdpGrowth": [{"year": 2015, "val": 2.7}, {"year": 2016, "val": -2.1}, {"year": 2017, "val": 2.9}, {"year": 2018, "val": -2.6}, {"year": 2019, "val": -2.0}, {"year": 2020, "val": -9.9}, {"year": 2021, "val": 10.7}, {"year": 2022, "val": 5.0}, {"year": 2023, "val": -1.6}], "sectors": [{"name": "服务业", "value": 53}, {"name": "工业", "value": 24}, {"name": "农业", "value": 7}], "exports": [{"name": "大豆/豆粕", "value": 25}, {"name": "玉米", "value": 10}, {"name": "牛肉", "value": 7}, {"name": "小麦", "value": 5}, {"name": "石油/天然气", "value": 12}], "inflation": 133.0, "unemployment": 5.7, "tradeBalance": 14000000000, "mainPartners": ["巴西", "中国", "美国", "智利"], "debtToGdp": 89.0, "fdi": 7000000000, "exchangeRate": "约900 ARS/USD (官方) / 1300+ (黑市)", "mainCompanies": "YPF (石油，部分国有), Techint (钢铁), MercadoLibre (电商), Grupo Clarin (媒体)"}, "society": {"literacy": 99.0, "lifeExpectancy": 76.9, "urbanization": 92, "povertyRate": 41.7, "homicideRate": 4.3, "educationExp": 5.1, "healthExp": 9.5, "ethnic": "白人/混血 (97%), 印第安人 (2%), 其他 (1%)", "internetPenetration": 87, "fertilityRate": 1.9, "gii": 0.304, "climateRisk": "高：极端天气事件（干旱和洪水交替）、巴塔哥尼亚冰川融化。", "refugees": "接收约20万委内瑞拉难民；本国人口外流至西班牙、美国和意大利。"}},
  URY: {"population": 3426000, "area": 176215, "language": "西班牙语", "currency": "比索 (UYU)", "gdp": 82000000000, "gdpPerCapita": 24000, "gini": 39.7, "hdi": 0.809, "overview": "乌拉圭是拉美最世俗化、最平等和最稳定民主国家之一。2009-2010年成为世界上首个全面大麻合法化国家。前总统穆希卡以简朴生活闻名全球。社会福利体系完善，但经济增长缓慢。", "history": [{"year": "前10000", "event": "查鲁亚等印第安部落定居"}, {"year": "1516", "event": "西班牙探险队抵达，但印第安人激烈抵抗使殖民延迟"}, {"year": "1680", "event": "葡萄牙建立科洛尼亚据点"}, {"year": "1726", "event": "西班牙建立蒙得维的亚以对抗葡萄牙"}, {"year": "1777", "event": "根据圣伊尔德丰索条约，西班牙确认对乌拉圭的主权"}, {"year": "1811", "event": "何塞赫瓦西奥阿蒂加斯发动独立运动"}, {"year": "1816-1820", "event": "葡萄牙（后为巴西）占领乌拉圭"}, {"year": "1825", "event": "33名爱国者起义，摆脱巴西和阿根廷争夺，独立建国"}, {"year": "1828", "event": "英国调停，阿根廷和巴西承认乌拉圭独立"}, {"year": "1836-1852", "event": "内战，红党（保守城市派）与白党（自由农村派）对抗"}, {"year": "1865-1870", "event": "三国同盟战争，乌拉圭与巴西阿根廷对抗巴拉圭"}, {"year": "1903-1907", "event": "巴特列奥多涅斯总统，现代福利国家奠基人"}, {"year": "1911-1915", "event": "巴特列再次执政，推行激进社会改革（8小时工作制、离婚、世俗教育）"}, {"year": "1933", "event": "特拉总统政变"}, {"year": "1942", "event": "颁布新宪法，恢复民主制度"}, {"year": "1952-1967", "event": "集体执政制度（9人执政委员会）"}, {"year": "1967", "event": "恢复总统制，通过新宪法"}, {"year": "1973-1985", "event": "军人执政，为乌拉圭历史上唯一的独裁时期"}, {"year": "1980", "event": "军政府宪法草案被公投否决"}, {"year": "1984", "event": "恢复民主谈判（海军俱乐部协定）"}, {"year": "1985", "event": "桑吉内蒂当选总统，文人政府回归"}, {"year": "2005-2010", "event": "塔瓦雷巴斯克斯首次执政，广泛阵线成为首个左翼政府"}, {"year": "2010-2015", "event": "何塞穆希卡执政，被誉为世界最穷总统，推动大麻合法化"}, {"year": "2013", "event": "通过全面大麻合法化法案，世界首个"}, {"year": "2017", "event": "通过跨性别权利法案"}, {"year": "2020", "event": "COVID期间保持相对较低的死亡率"}, {"year": "2024", "event": "亚曼杜奥尔西当选，广泛阵线在执政15年后2019年失利，2024年重夺执政权"}], "politics": {"system": "总统制共和国", "headOfState": "亚曼杜奥尔西", "rulingParty": "广泛阵线 (FA)", "legislature": "两院制：参议院30席，众议院99席", "lastElection": "2024年", "notes": "奥尔西为前总统巴斯克斯的农业部长，广泛阵线在执政15年后2019年失利，2024年重夺执政权。", "constitutionalHistory": "1967年宪法，历经修正。1996年修宪引入两轮选举制。", "foreignRelations": "巴西和阿根廷为最重要伙伴。与中国签署自贸协定谈判。在拉美人权议题上立场积极。", "internationalOrgs": ["联合国", "Mercosur", "美洲国家组织 (OAS)", "CELAC"]}, "economy": {"gdpGrowth": [{"year": 2015, "val": 0.4}, {"year": 2016, "val": 1.7}, {"year": 2017, "val": 1.6}, {"year": 2018, "val": 0.5}, {"year": 2019, "val": 0.4}, {"year": 2020, "val": -5.9}, {"year": 2021, "val": 4.4}, {"year": 2022, "val": 4.9}, {"year": 2023, "val": 0.4}], "sectors": [{"name": "服务业", "value": 66}, {"name": "工业", "value": 22}, {"name": "农业", "value": 6}], "exports": [{"name": "牛肉", "value": 18}, {"name": "大豆", "value": 15}, {"name": "纸浆", "value": 12}, {"name": "大米", "value": 6}, {"name": "乳制品", "value": 5}], "inflation": 5.1, "unemployment": 7.8, "tradeBalance": -800000000, "mainPartners": ["中国", "巴西", "阿根廷", "美国"], "debtToGdp": 59.0, "fdi": 2500000000, "exchangeRate": "39 UYU/USD", "mainCompanies": "Conaprole (乳制品), UPM (纸浆), Tata (软件外包), Banco Itau (金融)"}, "society": {"literacy": 98.8, "lifeExpectancy": 78.1, "urbanization": 96, "povertyRate": 9.9, "homicideRate": 10.1, "educationExp": 4.9, "healthExp": 8.5, "ethnic": "白人 (88%), 混血 (8%), 非裔 (4%)", "internetPenetration": 90, "fertilityRate": 1.8, "gii": 0.232, "climateRisk": "中高：干旱、洪水、极端天气。在可再生能源和气候政策上走在拉美前列。", "refugees": "接收少量邻国难民；本国人口外流较少，为高生活质量吸引移民目的地。"}},
};
